<?php $this->content->begin() ?>
<div class="left main-content">
    <p style="font-family: Arial, Helvetica, sans-serif; font-size: 12pt; font-weight: bold; text-transform: uppercase; color: red;"><?php echo $error?></p>
</div>
<div class="left sidebar">
    <div class="leftmenu">
        <ul>
            <li><a href="<?php echo $this->url->action('index')?>">Tất cả video</a></li>
            <li><a href="<?php echo $this->url->action('last')?>">Video mới</a></li>
            <li><a href="<?php echo $this->url->action('mostView')?>">Xem nhiều nhất</a></li>
            <li><a href="<?php echo $this->url->action('mostRate')?>">Bình chọn nhiều nhất</a></li>
        </ul>
    </div>
</div>
<div class="cl"></div>
<?php $this->content->end()?>