<?php $this->content->begin()?>
<div class="left main-content">
    <div class="title">Video mới nhất</div>
    <div class="l-content video">
        <ul>
            <?php $i = 1; foreach ($videos as $video): ?>
            <?php if(empty($video->avatar)) $video->avatar = $this->url->content('Content/LNGuitar/images/no-avatar.png')?>
            <li <?php if ($i % 4 == 0) { ?>class="last"<?php }?>>
                <img src="<?php echo $video->avatar ?>"/>
                <a class="tit" href="<?php echo $this->url->action('detail', array('seo_url' => $video->seo_url, 'id' => $video->id))?>"><?php echo $video->title ?></a>
                <p class="vd">Lượt xem: <?php echo $video->hit ?></p>
            </li>
            <?php $i++; endforeach; ?>
        </ul>
        <div class="cl"></div>
    </div>
    <?php $this->widget->create('Standard_SPagination', array('template' => 'ulli',
                                                              'count'    => $count,
                                                              'limit'    => $limit,
                                                              'current_page'    => $page));?>
    <div class="cl"></div>
</div>
<div class="left sidebar">
    <div class="leftmenu">
        <ul>
            <li><a href="<?php echo $this->url->action('index')?>">Tất cả video</a></li>
            <li class="current"><a href="javascript:void();">Video mới</a></li>
            <li><a href="<?php echo $this->url->action('mostView')?>">Xem nhiều nhất</a></li>
            <li><a href="<?php echo $this->url->action('mostRate')?>">Bình chọn nhiều nhất</a></li>
        </ul>
    </div>
    <a class="sidebox-title" style="margin-top: 26px;">Danh mục</a>
    <div class="leftmenu">
        <ul>
            <?php foreach($categories as $c):?>
            <li><a href="<?php echo $this->url->action('category', array('seo_url' => $c->seo_url, 'id' => $c->id))?>"><?php echo $c->name?></a></li>
            <?php endforeach?>
        </ul>
    </div>
</div>
<div class="cl"></div>
<?php $this->content->end()?>