<?php
$first = 0;
$last = count($moreVideos);


function getClass($first, $last) {
    if($first == 1) return "first top left left-phone";
    elseif($first == $last) return "last";
    elseif($first % 2 == 0) return "top left";
    else return "left left";
}
?>
<?php foreach($moreVideos as $video):?>

    <?php $first++;?>
    <div class="blockVideo <?php echo getClass($first, $last);?>">
        <div class="videoPirmary">
            <img style="width: 159px;height: 108px" src="<?php echo $video->avatar ?>" />
        </div>
        <div class="blockTitle"><a href="javascript:void(0);" onclick="playVideo(<?php echo $video->id?>)"><?php echo $video->title?></a></div>
        <div class="clearfix"></div>
    </div>
<?php endforeach;?>

<script>
    function playVideo(id_video) {
        $("#playVideo").load("/Video/Index/playVideo/"+id_video);
    }

    $(document).ready(function(){
        var num = document.getElementById("page").value;
        var max = <?php echo $last;?>;

        if(num > 1) $("#pre").show();
        else $("#pre").hide();

        if(max < 4) $("#next").hide();
        else $("#next").show();
    });
</script>