<div class="blockTitle"><a href="#"><?php echo $playVideo->title?></a></div>
<div class="videoPirmary">
    <!--<img src="images/contents/video-big.png" width="100%" />-->
    <?php echo getEmbedCode($playVideo->url);?>
</div>

<?php
function getEmbedCode($url) {
    $step1=explode('v=', $url);
    $step2 =explode('&',$step1[1]);
    $vedio_id = $step2[0];

    $embedCode = '<iframe width="100%" height="100%" src="http://www.youtube.com/embed/'. $vedio_id.'" frameborder="0"></iframe>';
    return $embedCode;
}
?>