<div class="l-content video">
    <ul>
        <?php $i = 1; foreach ($videos as $video): ?>
        <?php if(empty($video->avatar)) $video->avatar = $this->url->content('Content/LNGuitar/images/no-avatar.png')?>
        <li <?php if ($i % 4 == 0) { ?>class="last"<?php }?>>
            <a href="<?php echo $this->url->action('detail', 'Index', array('seo_url' => $video->seo_url, 'id' => $video->id))?>" title="<?php echo $video->title ?>"><img src="<?php echo $video->avatar ?>"/></a>
            <a class="tit" href="<?php echo $this->url->action('detail', 'Index', array('seo_url' => $video->seo_url, 'id' => $video->id))?>" title="<?php echo $video->title ?>"><?php echo XPHP_String::shortenText($video->title, 50) ?></a>
            <p class="vd">Lượt xem: <?php echo $video->hit ?></p>
        </li>
        <?php $i++; endforeach; ?>
    </ul>
    <div class="cl"></div>
</div>