    <h2 style="background-color: #2694e8; color: black">
        <a style="background-color: #2694e8; color: #FF4800;" href="<?php echo $this->url->action('category','Index','Image', array('page'=> 1)) ?>">
            Bộ sưu tập ảnh <img style="float: right; height: 13px; margin-right: 5px;" src="http://9day.vn/Content/mg24h/Content/hot1.gif">
        </a>
    </h2>
    <div id="hpage_latest">
        <ul>
            <?php $i=1; foreach($albums as $news): ?>
            <li <?php if($i %4 ==0): ?> class="last" <?php endif; ?>>
                <img style="width: 190px; height: 130px;" src="<?php echo $news->image ?>" alt="<?php echo $news->name ?>" />
                <p class="readmore"><a href="<?php echo $this->url->action('detail','Index','Image', array('seo_url' => $news->seo_url,'id'=>$news->id)) ?>"><?php echo $news->name ?></a></p>                
            </li>
            <?php $i++; endforeach; ?>
        </ul>        
        <br class="clear" />
        <p class="readmore"><a href="<?php echo $this->url->action('category','Index','Image', array('page'=> 1)) ?>">Xem thêm >> </a></p>
    </div>