<?php $this->content->begin() ?>
<div class="fll left-content">
    <div class="box-gioithieu">
        <ul class="tabgt spr pRel">
            <li class="fll"><span>Tài liệu</span></li>
            <span class="pAbs navi-dt"><a href="<?php echo $this->url->action('index', "Index", "") ?>">Trang chủ</a></span>
        </ul>
        <div class="content-gioithieu">
            <select name="choosecate" id="choosecate">
                <?php foreach ($catOptions as $key => $cate): ?>
                <option <?php if($category_id == $key): ?> selected="selected" <?php endif; ?> value="<?php echo $key; ?>"><?php echo $cate; ?></option>
                <?php endforeach; ?>
            </select> <br /><br />
            <script>
                $(document).ready(function(){
                    $('#choosecate').change(function(){
                        if(document.location.search.length) {
                            window.location.href = "/an-pham.html?page=" + <?php echo $page ?> + "&id=" + $(this).val();
                        } else {
                            window.location.href = "/an-pham.html" + "?id=" + $(this).val();
                        }
                        
                    });
                });
                
                
            </script>
<table>
    <tr>
        <td style="width: 20%;">Số/Ký hiệu</td>
        <td style="width: 20%;">Ngày ban hành</td>
        <td style="width: 40%;">Trích yếu</td>
        <td style="width: 40%;">Xem trước</td>
        <td style="width: 20%;">Tải về</td>
    </tr>
    <?php foreach($articals as $value): ?>
    <tr>
        <td style="text-align: left;"><?php echo  $value->number; ?></td>
        <td style="text-align: left;"><?php echo $value->date_start; ?></td>
        <td style="text-align: left;"><?php echo $value->description; ?></td>
        <td>
            <a href="<?php echo $this->url->action('view','Index','Document', array('id' => $value->id)); ?>" >Xem trước</a>
        </td>
        <td>
            <?php if(isset($_SESSION['username'])): ?>
            <a href="<?php echo $value->file; ?>" ><img style="width: 16px; height: 16px;" src="https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/download.png"></a>
            <?php else: ?>
            <a href="<?php echo $this->url->action('index','Index','') ?>" >Đăng nhập để download!</a>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
           <div class="paging">
                <ul class="box-page rs cf">
                    <?php if ($page > 2): ?><li class="fll"><a href="<?php echo $this->url->action('index', 'Index', 'Document') . "?page=" . ($page - 2) ?>" class="active"><?php echo $page - 2; ?></a></li><?php endif; ?>
                    <?php if ($page > 1): ?><li class="fll"><a href="<?php echo $this->url->action('index', 'Index', 'Document') . "?page=" . ($page - 1) ?>" class="active"><?php echo $page - 1; ?></a></li><?php endif; ?>
                    <li class="fll"><a href="<?php echo $this->url->action('index', 'Index', 'Document') . "?page=" . ($page) ?>"><?php echo $page ?></a></li>
                    <?php if ($page * $limit <= $count): ?><li class="fll"><a href="<?php echo $this->url->action('index', 'Index', 'Document') . "?page=" . ($page + 1) ?>"><?php echo $page + 1 ?></a></li> <?php endif; ?>
                    <?php if (($page + 1) * $limit  <= $count): ?><li class="fll"><a href="<?php echo $this->url->action('index', 'Index', 'Document') . "?page=" . ($page + 2) ?>"><?php echo $page + 2 ?></a></li><?php endif; ?>
                </ul>

            </div> 
            
            </div>
        
        </div>
    </div>
<?php $this->content->end()?>