<div class="blockContent">
    <table class="responsive">
        <thead>
        <tr>
            <th>STT</th>
            <th >Category</th>
            <th class="left">Title</th>
            <th>File size</th>
            <th>File type</th>
            <th>Download total</th>
            <th>Download file</th>
        </tr>
        </thead>
        <tbody>
        <?php $i=1; foreach($result_pag_data as $data): ?>
        <tr>
            <td class="left"><?php echo $i ?></td>
            <td ><?php echo $result_document_cat[$data->resource_category_id]->category_title ?></td>
            <td class="left title"><?php echo $data->title ?></td>
            <td><?php echo $result_data_infos[$data->resource_id]->file_size ?> bytes</td>
            <td><?php echo $result_data_infos[$data->resource_id]->filename ?></td>
            <td><?php echo $result_resource_version[$data->resource_id]->download_count ?></td>
            <td><a href="<?php echo "http://vncpc.vn/forum/resources/resource-id.{$data->resource_id}/download?version={$result_resource_version[$data->resource_id]->resource_version_id}"; ?>">
                    <img src="<?php echo $this->url->content("Content/VNCPC/images/icons/pdf.png") ?>" />
                </a>
            </td>
        </tr>
        <?php $i++; endforeach;?>
        </tbody>
    </table>

    <div class="pageNav">
        <?php if ($first_btn): ?>
            <a href="javascript:void (0)" p="1" class="prev"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/prev.png") ?>" /></a>
        <?php endif;?>
        <?php for ($i = $start_loop; $i <= $end_loop; $i++) :?>

            <?php if ($cur_page == $i) :?>
                <a href="javascript:void (0)" p='<?php echo $i?>' class='current'><?php echo $i?></a>
            <?php else:?>
                <a href="javascript:void (0)" p='<?php echo $i?>'><?php echo $i?></a>
            <?php endif;?>
        <?php endfor;?>
        <?php if ($last_btn):?>
            <a href="javascript:void (0)" p='<?php echo $no_of_paginations?>' class='next'><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/next.png")?>" /></a>
        <?php endif;?>
    </div>
    <div class="clearfix"></div>

</div>
