<?php $this->content->begin()?>
<div class="content fullwidth">
    <div class="login-page">
        <div class="login-form">
            <div class="title-none-bg no-margin">Đăng nhập</div>
            <div class="login-form-f">
                <?php $this->form->begin('loginPanel')?>
                <table cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <td><label for="username">Tên đăng nhập:</label></td>
                        <td>
                            <?php $this->form->textboxFor('username', array('class' => 'inputtxt', 'placeholder' => 'Tên đăng nhập'))?>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="password">Mật khẩu:</label></td>
                        <td>
                            <?php $this->form->passwordFor('password', array('class' => 'txt inputtxt', 'placeholder' => 'Mật khẩu'))?>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="remember">Luôn ở trạng thái đăng nhập:</label></td>
                        <td>
                            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                <tr>
                                    <td><input type="checkbox" name="remember" id="remember" value="1" /></td>
                                    <td align="right">
                                        <a href="#" class="forgot">Bạn quên mật khẩu</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="right">
                            <p class="error" style="color: red; font-size: 12px; margin-top: 15px; display: none"></p>
                            <p class="loading" style="margin-top: 15px; display: none"><img src="<?php echo $this->url->content('Content/LNGuitar/images/login_loading.gif')?>" /></p>
                            <input type="submit" value="Đăng nhập" class="submit" />
                        </td>
                    </tr>
                </table>
                <?php $this->form->end()?>
            </div>
        </div>
        <div class="login-facebook">
            <div class="title-none-bg no-margin">Đăng nhập tài khoản facebook</div>
            <p>Bạn có thể đăng nhập bằng tài khoản Facebook của mình</p>
            <a href="#" class="btn-login-facebook">Đăng nhập với facebook</a>
        </div>
    </div>
    <div class="cl"></div>
</div>
<script type="text/javascript">
    $(function(){
        $('#loginPanel').submit(function(e){
            e.preventDefault();
            $('.loading').show();
            $.ajax({
                data: $('#loginPanel').serialize(),
                type: "POST",
                success: function(res){
                    $('.loading').hide();
                    if(res.success)
                        window.location.href = res.url;
                    else
                    {
                        $('.error').html(res.message).show();
                    }
                }
            });
        });
    });
</script>
<?php $this->content->end()?>