<?php $this->content->begin()?>
<div class="widget">
    <div class="header">
        <span><span class="ico  gray paragraph_justify"></span> Sửa danh mục bài viết </span>
    </div><!-- End header -->
    <div class="content">
        <div class="formEl_b">
            <?php
            $ajaxOption['begin'] = "begin";
            $ajaxOption['success'] = "success";
            $this->form->beginAjax($ajaxOption);
            ?>
            <?php $this->form->hiddenFor('id')?>
            <fieldset>
                <legend>Thông tin danh mục</legend>
                <div class="section">
                    <?php $this->form->labelFor("parent_id")?>
                    <div>
                        <?php $this->form->selectFor("parent_id", $catOptions , null, null, array('data-placeholder' => "Lựa chọn danh mục cha...",
                                                                                                  'onkeyup' => "updateSeoUrl(this, '#seo_url')"))?>
                        <label class="red">*</label>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("name")?>
                    <div>
                        <?php $this->form->textboxFor("name", array('class' => "large"))?>
                        <label class="red">*</label>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("seo_url")?>
                    <div>
                        <?php $this->form->textboxFor("seo_url", array('class' => 'large'))?>
                        <a class="regenerate_seo_url" onclick="updateSeoUrl('#name', '#seo_url')">
                            <span class="ico color reload"></span>
                        </a>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("image")?>
                    <div>
                        <?php $this->form->textboxFor("image", array('class' => "medium"))?>
                        <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="image" >open</a>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("sort")?>
                    <div>
                        <?php $this->form->textboxFor("sort", array('class' => "small"))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("description")?>
                    <div>
                        <?php $this->form->textareaFor("description", array('class' => "editor", 'cols' => "", 'rows' => ""))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("seo_keyword")?>
                    <div>
                        <?php $this->form->textboxFor("seo_keyword", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("seo_description")?>
                    <div>
                        <?php $this->form->textAreaFor("seo_description", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section last">
                    <div>
                        <input class="uibutton icon add" id="submit" type="submit" value="Cập nhật">
                        <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                        <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("index")?>">Danh mục bài viết</a>
                    </div>
                </div>
            </fieldset>
            <?php $this->form->end()?>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin('stylesheets')?>
<style type="text/css">
    .cleditorMain{
        height: 180px !important;
    }
</style>
<?php $this->section->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js'));
?>
<script type="text/javascript">
    $(function(){
        // Select boxes
        $("select").not("select.chzn-select").selectBox();
    });
</script>
<script type="text/javascript">
    $(function(){
        $("#item_type").change(function(){
            $.ajax({
                url: $(this).data('url'),
                type: "post",
                data: {item_type: $(this).val()},
                success: function(res){
                    $("#menu_type_container").html(res);
                    $('#menu_type_container select').selectBox();
                }
            });
        });
        $("#item_type").change();
    });
</script>
<?php $this->section->end()?>