<?php $this->content->begin()?>
<div class="widget">
    <div class="header">
        <span><span class="ico  gray paragraph_justify"></span> Danh mục bài viết </span>
    </div><!-- End header -->
    <div class="content">
        <?php $this->form->begin('orderList', array('data-delete-url' => $this->url->action('delete'),
                                                    'data-edit-url'   => $this->url->action('edit')))?>
        <?php echo $htmlCatMultiLevel?>
        <div class="global-form-footer">
            <input class="uibutton large icon edit" id="submit" type="submit" value="Cập nhật" style="width: 200px;">
            <a class="uibutton special large icon add" href="<?php echo $this->url->action("create")?>">Thêm danh mục mới</a>
        </div>
        <?php $this->form->end()?>
    </div>
</div>
<div id="dialogDelete" style="display: none"></div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/confirm/jquery.confirm.js',
                          'Content/XMin/js/jquery.ui.nestedSortable.js',
                          'Application/Modules/Artical/Assets/js/index_articalcategory.js'));
?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
<?php
//Load css
$this->html->loadCss('Application/Modules/Artical/Assets/css/index_articalcategory.css');
?>
<?php $this->section->end()?>