<div class="box-cnt box-videos">
    <?php $i=1; foreach($videoInfo as $video): ?>
    <div class="vitem <?php if($i%2==0){?> last <?php }?>">
        <img class="vitem-img" src="<?php echo $video->avatar ?>" width="110" height="72" />
        <a class="vitem-title" href="<?php echo $this->url->action('detail','Index','Video', array($video->id)) ?>"><?php echo $video->title ?></a>
        <p class="vitem-count">Lượt xem: <?php echo $video->hit ?></p>
    </div>
    <?php $i++; endforeach; ?>
    <div class="cl"></div>
    <a class="seemore" href="<?php echo $this->url->action('index', 'Index')?>">Xem tiếp »</a>
    <div class="cl"></div>
</div>