<?php $this->section->begin('breadcrumb')?>
<div id="global-breadcrumb">
	<ul>
		<li class="current">Trang nội dung</li>
	</ul>
</div>
<?php $this->section->end()?>
<?php $this->content->begin()?>
<div class="widget-shell inner-shadow">
	<div class="widget-header">
		<h2>Trang nội dung</h2>
	</div>
	<div class="widget-body">
		<div class="fclear"></div>
		<?php $this->widget->widget("KendoUI_Grid", array("id" => "pageList", 
														  "dataSource" => $dataSource,
		                                                  "height" => 600,
		                                                  "filterable" => true,
		                                                  "groupable" => true,
                                                          "scrollable" => true,
                                                          "sortable" => array("mode" => "single",
                                                                              "allowUnsort" => false),
                                                          "pageable" => true,
		                                                  "columns" => array(
		                                                                   "date_create" => array("template" => "#= kendo.toString(date_create, 'MM/dd/yyyy')#")
		                                                               )
		                                             ));?>
		<div class="fclear"></div>
		<div class="global-form-footer">
			<a href="<?php echo $this->url->action("create")?>" class="button">
				<span class="ico-text ico-text-brainstorm"></span>Thêm trang nội dung
			</a>
		</div>
	</div>
</div>
<div title="Xác nhận xóa tin tức" id="deleteDialog"></div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>

<?php $this->section->end()?>
