 <?php $this->content->begin()?>
 <div class="widget">
     <div class="header">
         <span><span class="ico  gray paragraph_justify"></span> Thêm Video mới </span>
     </div><!-- End header -->
     <div class="content">
         <div class="formEl_b">
             <?php
             $ajaxOption['begin'] = "begin";
             $ajaxOption['success'] = "success";
             $this->form->beginAjax($ajaxOption);
             ?>
             <?php $this->form->hiddenFor('id') ?>
             <?php $this->form->hiddenFor('author_id') ?>
             <?php $this->form->hiddenFor('hit') ?>
             <?php $this->form->hiddenFor('fav_count') ?>
             <?php $this->form->hiddenFor('rate_count') ?>
             <?php $this->form->hiddenFor('rate_point') ?>
             <?php $this->form->hiddenFor('rate_avg') ?>
                 <fieldset>
                     <legend>Thông tin menu</legend>
                     <div class="section">
                         <?php $this->form->labelFor("category_id")?>
                         <div>
                             <?php $this->form->selectFor('category_id', $categoryOptions)?>
                             <label class="red" for="category_id">*</label>
                         </div>
                     </div>
                     <div class="section">
                        <?php $this->form->labelFor("url")?>
                        <div>
                            <?php $this->form->textboxFor("url", array('class' => "medium", "onchange"=>"getYouTubeInfo(this)"))?>                            
                            <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="url" >open</a>                            
                        </div>
                    </div>
                     <div class="section">
                         <?php $this->form->labelFor("title")?>
                         <div>
                             <?php $this->form->textboxFor("title", array('class' => "medium",'onkeyup' => "updateSeoUrl(this, '#seo_url')"))?>
                             <label class="red">*</label>
                         </div>
                     </div>
                     <div class="section">
                         <?php $this->form->labelFor("seo_url")?>
                         <div>
                            <?php $this->form->textboxFor("seo_url", array('class' => "large"))?>
                             <label class="red">*</label>
                         </div>
                     </div>
                     <div class="section">
                         <?php $this->form->labelFor("description")?>
                         <div>
                            <?php $this->form->textboxFor("description", array('class' => "large"))?>
                         </div>
                     </div>
                     <div class="section">
                        <?php $this->form->labelFor("lyric")?>
                        <div>
                            <?php $this->form->textareaFor("lyric", array('id' => 'content-editor'))?>
                        </div>
                    </div>
                    <div class="section">
                        <?php $this->form->labelFor("avatar")?>
                        <div>
                            <?php $this->form->textboxFor("avatar", array('class' => "medium"))?>                            
                            <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="avatar" >open</a>                            
                        </div>
                    </div>                     
                     <div class="section">
                         <?php $this->form->labelFor("sort")?>
                         <div>
                            <?php $this->form->textboxFor("sort")?>
                         </div>
                     </div>                     
                     <div class="section">
                         <?php $this->form->labelFor("seo_keyword")?>
                         <div>
                            <?php $this->form->textboxFor("seo_keyword", array('class' => "large"))?>
                         </div>
                     </div>
                     <div class="section">
                         <?php $this->form->labelFor("seo_description")?>
                         <div>
                            <?php $this->form->textboxFor("seo_description", array('class' => "large"))?>
                         </div>
                     </div>
                     <div class="section last">
                         <div>
                             <input type="hidden" name="saveType" value="0" id="saveType" />
                        <input class="uibutton icon add" id="submit" type="submit" value="Sửa">
                        <input class="uibutton icon add" id="submit2" type="submit" value="Sửa và đóng" onclick="$('#saveType').val('1');">
                             <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                             <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("index")?>">Danh sách Video</a>
                         </div>
                     </div>
                 </fieldset>
             <?php $this->form->end()?>
         </div>
     </div>
 </div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<?php 
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Assets/tiny_mce/tiny_mce.js',
                          'Assets/tiny_mce/plugins/imagemanager/js/mcimagemanager.js',
                          'Application/Modules/Video/Assets/js/tinymce.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js'));
?>
<script type="text/javascript">
    $(function(){
        // Select boxes
        $("select").not("select.chzn-select").selectBox();
    });
</script>
<script>
function getYouTubeInfo(e){
    url = $(e).val();
    id = url.split("v=")[1].substring(0, 11);
    $.getJSON("http://gdata.youtube.com/feeds/api/videos/"+id+"?v=2&alt=jsonc&callback=?", function(json){
        $('#title').val(json.data.title);
        html = "";
        html += "Người upload: "+json.data.uploader+"<br>";
        html += "Thể loại: "+json.data.category+"<br>";
        html +=json.data.description;        
        $('#avatar').val(json.data.thumbnail.hqDefault);
        $('#url').val("http://www.youtube.com/watch?v="+id);
        tinyMCE.activeEditor.setContent(html);
        updateSeoUrl('#title', '#seo_url');
    });
}

</script>
<?php $this->section->end()?>