<?php $this->content->begin() ?>
<div class="content projectContent  partnerContent">
    <div class="firstContent">
        <div class="listTitle"><a href="<?php echo $this->url->action('index','Index','Page') ?>">About Us</a> > <a>Partners</a></div>
        <div class="listProjects">
            <?php if(isset($albums[0])): ?>
            <div class="blockProject left first left-tablet">
                <div class="blockImage"><a href="#">
                        <img style="width:200px;height:165px;" src="/Thumb/phpThumb.php?src=<?php echo str_replace('http://vncpc.vn', '', $albums[0]->file) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="#"><?php echo $albums[0]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[0]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[1])): ?>
            <div class="blockProject left">
                <div class="blockImage"><a href="#">
                        <img style="width:200px;height:165px;" src="/Thumb/phpThumb.php?src=<?php echo str_replace('http://vncpc.vn', '', $albums[1]->file) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="#"><?php echo $albums[1]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[1]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[2])): ?>
            <div class="blockProject left left-tablet">
                <div class="blockImage"><a href="#">
                        <img style="width:200px;height:165px;" src="/Thumb/phpThumb.php?src=<?php echo str_replace('http://vncpc.vn', '', $albums[2]->file) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="#"><?php echo $albums[2]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[2]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[3])): ?>
            <div class="blockProject">
                <div class="blockImage"><a href="#">
                        <img style="width:200px;height:165px;" src="/Thumb/phpThumb.php?src=<?php echo str_replace('http://vncpc.vn', '', $albums[3]->file) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="#"><?php echo $albums[3]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[3]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <div class="clearfix"></div>
        </div>
        <div class="controlBlock">
            <?php if($page > 1): ?>
            <a href="<?php echo $this->url->action('category','Index','Partner', array('page'=>$page-1)) ?>" class="prev"><img src="<?php echo $this->url->content('/Content/VNCPC/images/prev.png') ?>" /></a>
            <?php endif; ?>
            <?php if(count($albums) == $limit ): ?>
            <a href="<?php echo $this->url->action('category','Index','Partner', array('page'=>$page+1)) ?>" class="next"><img src="<?php echo $this->url->content('/Content/VNCPC/images/next.png') ?>" /></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php $this->content->end() ?>