<div class="blockTitle"><a href="<?php echo $this->url->action("index", "Index", "Page")?>">Giới thiệu</a> > <a href="#"><?php echo $artical->title; ?></a></div>
<div class="blockContent">
    <div class="blockContentImage" id="print">
        <?php echo $artical->content;?>
    </div>
    <div class="pageControl">
        <div class="topControl">
            Số lượt đọc: <strong><?php echo $artical->view_count +1;?></strong> - Cập nhật lần cuối: <strong>06/08/2013 10:50:06 AM</strong>
        </div>
        <div class="bottomControl">
            <a href="javascript:history.go(-1)"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/back.png")?>">Về trang trước</a>
            <a href="#" onClick="printF('print')"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/print.png")?>">Bản in</a>
            <a href="<?php echo $this->url->action("index", "Index", "Contact")?>"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/mail.png")?>">Gửi mail</a>
            <a href="#"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/totop.png")?>">Về đầu trang</a>
        </div>
        <div class="clearfix"></div>
    </div>
    <!--<div class="pageControl">
        <div class="topControl">
            S? L??t ??c: <strong>37708</strong> - C?p nh?t l?n cu?i: <strong>29/01/2008 10:50:06 PM</strong>
        </div>
        <div class="bottomControl">
            <a href="#"><img src="images/icons/back.png">V? trang tr??c</a>
            <a href="#"><img src="images/icons/print.png">B?n in</a>
            <a href="#"><img src="images/icons/mail.png">G?i mail</a>
            <a href="#"><img src="images/icons/totop.png">V? ??u trang</a>
        </div>
        <div class="clearfix"></div>
    </div>-->
</div>