<!-- ********************************************************************* -->
<!-- Begin Black Header with logo and Navigation -->
<div id="global-header-shell">
	<div id="global-header">
		<div id="txt-logo">
			<a href="http://xweb.vn">
				<img src="<?php echo $this->url->content("Content/XAdmin/img/logo.png")?>" style="padding-top: 10px;" />
			</a>
		</div>
		<ul id="control">
			<li class="no-dash"><span>Xin chào, <?php //echo $this->session->user->fullname?></span></li>
			<li>
				<a href="#">Settings</a>
				<ul id="style-switcher">
					<li><a href="#" id="page-width-control">Full Width</a></li>
					<li><a href="#" id="text-control">Larger Text</a></li>
				</ul>
			</li>
			<li>
				<a href="#" class="settings">Cấu hình</a>
				<ul>
					<li><a href="<?php echo $this->url->action("changePassword", "ControlPanel", "Profile")?>">Đổi mật khẩu</a></li>
					<li><a href="<?php echo $this->url->action("index", "ControlPanel", "Profile")?>">Cá nhân</a></li>
					<li><a href="<?php echo $this->url->action("logout", "ControlPanel", "Auth")?>">Đăng xuất</a></li>
				</ul>
			</li>
		</ul>
		<div class="fclear"></div>
	</div>
</div>
<!-- //End Black Header with Logo and Navigation -->
<!-- ********************************************************************* -->

<!-- XSystemAdmin - 
<div class="block">
	<div class="panel_elements">
		<ul class="panel_item">
			<li><a href="#">Private messages<span class="number">14</span></a></li>
			<li><a href="#">System Log<span class="number">52</span></a></li>
			<li><a href="#">Tin bài chờ xử lý<span class="number">6</span></a></li>
			<li><a href="#">Comments approval<span class="number">89</span></a></li>
			<li><a href="#">New users<span class="number">27</span></a></li>
			<li><a href="#">Settings</a></li>
			<li class="right"><a href="<?php echo $this->url->action("logout", "ControlPanel", "Auth")?>">Đăng xuất<span class="logout"></span></a></li>
		</ul>
	</div>
</div>
header -->
<!-- ********************************************************************* -->