<a class="logo" href="#"></a>
<form method="get" id="searchform" action="#">
	<input placeholder="Search..." type="text" name="s" id="s" />
</form>
<ul id="menu">
	<li><a href="<?php echo $this->url->action('index', 'ControlPanel', 'News')?>" class="active">Tin tức<span class="icon10"></span></a>
		<ul>
			<li><a href="<?php echo $this->url->action('index', 'CategoryCP', 'News')?>">Danh mục tin</a></li>
		</ul>
	</li>
	<li><a href="./forms.html">Example forms<span class="icon2"></span></a></li>
	<li><a href="./gallery.html">Image gallery<span class="icon3"></span></a></li>
	<li><a href="./calendar.html">Advanced calendar<span class="icon4"></span></a></li>
	<li><a href="./file_explorer.html">File explorer<span class="icon5"></span></a></li>
	<li><a href="./charts.html">Charts<span class="icon6"></span></a></li>
	<li><a href="./custom_elements.html">Custom Elements<span class="icon7"></span></a></li>
	<li><a href="./grid.html">Grid<span class="icon8"></span></a></li>
	<li><a href="./tables.html">Data Tables<span class="icon9"></span></a></li>
</ul>