<ul class="leftSideBarMenu">
<?php 
	foreach ($menu as $menuItem):
?>
	<li>
		<a href="<?php echo $menuItem->item_value?>" <?php if(empty($menuItem->subs)){?>class="NoChild"<?php }?>>
			<span><?php echo $menuItem->title?></span>
		</a>
		<?php if(!empty($menuItem->subs)):?>
		<ul style="display: none;" class="SubMenu">
			<?php foreach ($menuItem->subs as $sub):?>
			<li><a href="<?php echo $sub->item_value?>"><?php echo $sub->title?></a></li>
				<?php endforeach;?>
		</ul>
		<?php endif;?>
	</li>
<?php
	endforeach;
?>
</ul>