<?php $this->content->begin()?>
<div class="widget">
     <div class="header">
         <span><span class="ico gray document"></span> Thêm trang nội dung</span>
     </div><!-- End header -->
     <div class="content">
         <div class="formEl_b">
             <?php
                 $ajaxOption['begin'] = "begin";
                 $ajaxOption['success'] = "success";
                 $this->form->beginAjax($ajaxOption, "Create");
             ?>
             <fieldset>
                 <legend>Thông tin trang</legend>
                 <div class="section">
                     <?php $this->form->labelFor("title")?>
                     <div>
                         <?php $this->form->textboxFor("title", array('class' => 'large validate[required,maxSize[250]]',
                                                                      'onkeyup' => "updateSeoUrl(this, '#seo_url')"))?>
                         <label class="red">*</label>
                     </div>
                 </div>
                 <div class="section ">
                    <?php $this->form->labelFor("file")?>
                    <div>
                        <?php $this->form->textboxFor("file", array('class' => 'medium'))?>
                        <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="file" >open</a>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("project_id")?>
                    <div>
                        <?php $this->form->textboxFor("project_id", array('class' => 'large'))?>
                    </div>
                </div>
                 <div class="section">
                    <?php $this->form->labelFor("sponsor")?>
                    <div>
                        <?php $this->form->textboxFor("sponsor", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("region")?>
                    <div>
                        <?php $this->form->textboxFor("region", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("date_start")?>
                    <div>
                        <?php $this->form->textboxFor("date_start", array('class' => 'large'))?>
                    </div>
                </div>
                 <div class="section last">
                     <div>
                     <input type="hidden" name="saveType" value="0" id="saveType" />
                        <input class="uibutton icon add" id="submit" type="submit" value="Thêm">
                        <input class="uibutton icon add" id="submit2" type="submit" value="Thêm và đóng" onclick="$('#saveType').val('1');">
                     <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                     <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("index")?>">Trang nội dung</a>
                     </div>
                 </div>
             <?php $this->form->end()?>
         </div>
	</div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin('stylesheets')?>
<style type="text/css">
    .cleditorMain{
        height: 180px !important;
    }
</style>
<?php $this->section->end()?>
<?php $this->section->begin("scripts")?>
<?php 
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Assets/tiny_mce/tiny_mce.js',
                          'Assets/tiny_mce/plugins/imagemanager/js/mcimagemanager.js',
                          'Application/Modules/Page/Assets/js/tinymce.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js'));
?>
<?php $this->section->end()?>