<?php $this->content->begin()?>
<div class="widget">
    <div class="header">
        <span><span class="ico gray document"></span> Sửa slide "<?php echo $heading?>" </span>
    </div><!-- End header -->
    <div class="content">
        <div class="formEl_b">
            <?php
            $ajaxOption['begin'] = "begin";
            $ajaxOption['success'] = "success";
            $this->form->beginAjax($ajaxOption);
            $this->form->hiddenFor('id');
            $this->form->hiddenFor('type');
            ?>
            <fieldset>
                <legend>Thông tin slide</legend>
                <div class="section">
                    <?php $this->form->labelFor("name")?>
                    <div>
                        <?php $this->form->textboxFor("name", array('class' => 'large validate[required,maxSize[250]]'))?>
                        <label class="red">*</label>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("brief")?>
                    <div>
                        <?php $this->form->textboxFor("brief", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section ">
                    <?php $this->form->labelFor("sort")?>
                    <div>
                        <?php $this->form->textboxFor("sort", array('class' => 'small'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("link")?>
                    <div>
                        <?php $this->form->textboxFor("link", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("title")?>
                    <div>
                        <?php $this->form->textboxFor("title", array('class' => 'large'))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("image")?>
                    <div>
                        <?php $this->form->textboxFor("image", array('class' => 'medium'))?>
                        <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="image" >open</a>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("description")?>
                    <div>
                        <?php $this->form->textareaFor("description", array('class' => "editor", 'cols' => "", 'rows' => ""))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("html")?>
                    <div>
                        <?php $this->form->textAreaFor("html", array('id' => 'content-editor'))?>
                    </div>
                </div>
                <div class="section last">
                    <div>
                        <input type="hidden" name="saveType" value="0" id="saveType" />
                        <input class="uibutton icon add" id="submit" type="submit" value="Sửa">
                        <input class="uibutton icon add" id="submit2" type="submit" value="Sửa và đóng" onclick="$('#saveType').val('1');">
                        <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                        <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("list", array($type))?>"><?php echo $heading?></a>
                    </div>
                </div>
                <?php $this->form->end()?>
            </fieldset>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin('stylesheets')?>
<style type="text/css">
    .cleditorMain{
        height: 180px !important;
    }
</style>
<?php $this->section->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Assets/tiny_mce/tiny_mce.js',
                          'Assets/tiny_mce/plugins/imagemanager/js/mcimagemanager.js',
                          'Application/Modules/Page/Assets/js/tinymce.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js'));
?>
<?php $this->section->end()?>