<?php $this->content->begin()?>
<div class="widget">
    <div class="header">
        <span><span class="ico gray stop"></span> Sửa HTML Block </span>
    </div><!-- End header -->
    <div class="content">
        <div class="formEl_b">
            <?php
            $ajaxOption['begin'] = "begin";
            $ajaxOption['success'] = "success";
            $this->form->beginAjax($ajaxOption, "Edit");
            $this->form->hiddenFor('id');
            $this->form->hiddenFor('name');
            ?>
            <fieldset>
                <legend>Thông tin Block</legend>
                <div class="section">
                    <?php $this->form->labelFor("brief")?>
                    <div>
                        <?php $this->form->textareaFor("brief", array('class' => "editor", 'cols' => "", 'rows' => ""))?>
                    </div>
                </div>
                <div class="section">
                     <?php $this->form->labelFor("status")?>
                     <div>
                         <?php $this->form->checkboxFor("status", array("class" => "on_off_checkbox"))?>
                     </div>
                 </div>
                <div class="section">
                    <?php $this->form->labelFor("html")?>
                    <div>
                        <?php $this->form->textAreaFor("html", array('id' => 'content-editor'))?>
                    </div>
                </div>
                <div class="section last">
                    <div>
                        <input class="uibutton icon add" id="submit" type="submit" value="Cập nhật">
                        <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                        <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("index")?>">HTML Block</a>
                    </div>
                </div>
                <?php $this->form->end()?>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin('stylesheets')?>
<style type="text/css">
    .cleditorMain{
        height: 180px !important;
    }
</style>
<?php $this->section->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Assets/tiny_mce/tiny_mce.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js'));
?>
<script type="text/javascript">
    $(document).ready(function(){
        //TinyMCE
        tinyMCE.init({
            // General options
            mode: "exact",
            elements: "html",
            theme: "advanced",
            skin_variant: "silver",
            plugins: "imagemanager,filemanager,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,|,forecolor,backcolor",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,
            valid_elements : '*[*]',
            relative_urls : false,

            language: "en",

            width: '100%',
            height: 300
        });
    });
</script>
<?php $this->section->end()?>