<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico  gray stop"></span>HTML Block</span> </div>
    <div class="content">
        <div class="load_page tableToolbar">
            <ul class="uibutton-group">
                <li><a class="uibutton special deleteAll" href="/en/Block/ControlPanel/index">Danh sách Block tiếng anh</a></li>
            </ul>
            <div class="tableName toolbar">
                <h3>HTML Block</h3>
                <form id="tblForm" method="post" data-delete-url="<?php echo $this->url->action('delete')?>"
                                                 data-edit-url="<?php echo $this->url->action('edit')?>">
                    <table class="display" id="data_table" data-ajax-url="<?php echo $this->url->action('index')?>">
                        <thead>
                        <tr>
                            <th width="35">
                                <div class="checksquared"><input type="checkbox" id="checkAll1" class="checkAll" /><label for="checkAll1"></label></div>
                            </th>
                            <th width="50">ID</th>
                            <th width="100" align="left">Block</th>
                            <th width="300">Mô tả chức năng</th>
                            <th width="100">Quản lý</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<?php $this->html->loadJs(array('Scripts/functions.js',
                                'Content/XMin/components/datatables/dataTables.min.js',
                                'Content/XMin/components/datatables/ColVis.js',
                                'Content/XMin/components/confirm/jquery.confirm.js',
                                'Application/Modules/Block/Assets/js/index_controlpanel.js'))?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
<style type="text/css">
    .aleft{
        text-align: left;
    }
</style>
<?php $this->section->end()?>