<div id="slide">
    <?php foreach($slides as $slide):
    if(!empty($slide->link))
        $link = "onclick=\"window.location.href='" . $slide->link . "';\" style='cursor: pointer;'";
    else
        $link = "";
    ?>
    <img width="558" height="288" <?php echo $link?> src="<?php echo $slide->image?>" alt="<?php echo $slide->title?>" width="720" height="348" title="&lt;a href=&quot;<?php echo $slide->link?>&quot;&gt;<?php echo $slide->title?>&lt;/a&gt;" />
    <?php endforeach?>
</div>