<div class="blockTitle"><a href="<?php echo $this->url->action("index", "Index", "Artical")?>">Tin t?c</a> ><a href="#"><?php echo $detail->title?></a></div>
<div class="blockContent">
    <div class="blockContentImage" id="print">
        <?php echo $detail->content?>

    </div>
    <div class="pageControl">
        <div class="fb-like" data-href="http://localhost/vnc/" data-send="false" data-layout="button_count" data-width="44" data-show-faces="false" data-font="arial"></div>
        <div class="topControl">
            S? L??t ??c: <strong><?php echo $detail->view_count +1;?></strong> - Cập nhật lần cuối: <strong><?php echo date('h:i:s d/m/Y',strtotime($detail->created_date))?></strong>
        </div>
        <div class="bottomControl">
            <a href="javascript:history.go(-1)"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/back.png")?>">Về trang trướcc</a>
            <a href="#" onClick="printF('print')"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/print.png")?>">Bản in</a>
            <a href="<?php echo $this->url->action("index", "Index", "Contact")?>"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/mail.png")?>">Gửi mail</a>
            <a href="#"><img src="<?php echo $this->url->content("/template/images/icons/totop.png")?>">V? ??u trang</a>
        </div>
        <div class="fb-comments" data-href="http://example.com" data-width="613" data-num-posts="5"></div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="clearfix"></div>