<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <title>XWEB XAdmin - <?php echo $title?></title>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <?php $this->html->loadCss(array("Content/XMin/css/xmin.style.css"))?>
    <style type="text/css">
        html {
            background-image: none;
        }
        label.iPhoneCheckLabelOn span {
            padding-left:0px
        }
        #versionBar {
            background-color:#212121;
            position:fixed;
            width:100%;
            height:35px;
            bottom:0;
            left:0;
            text-align:center;
            line-height:35px;
            z-index:11;
            -webkit-box-shadow: black 0px 10px 10px -10px inset;
            -moz-box-shadow: black 0px 10px 10px -10px inset;
            box-shadow: black 0px 10px 10px -10px inset;
        }
        .copyright{
            text-align:center; font-size:10px; color:#CCC;
        }
        .copyright a{
            color:#A31F1A; text-decoration:none
        }
    </style>
<body>
<div id="alertMessage">Đăng nhập không thành công</div>
<div id="successLogin"></div>
<div class="text_success">
    <img src="/Content/XMin/images/loadder/loader_green.gif" alt="XAdmin"><span>Chờ trong giây lát</span>
</div>
<div id="login">
    <div class="ribbon"></div>
    <div class="inner">
        <div class="logo"><img src="/Content/XMin/images/logo/logo_login.png" alt="XAdmin" /></div>
        <div class="formLogin">
            <?php $this->form->begin("formLogin")?>
                <div class="tip">
                    <?php $this->form->textboxFor("username", array('original-title' => "Tên đăng nhập"))?>
                </div>
                <div class="tip">
                    <?php $this->form->passwordFor("password", array('original-title' => "Mật khẩu"))?>
                </div>
                <div class="loginButton">
                    <div style="float:left; margin-left:-9px;">
                        <input type="checkbox" id="on_off" name="remember" class="on_off_checkbox"  value="1" />
                        <span class="f_help">Ghi nhớ</span>
                    </div>
                    <div style="float:right; padding:3px 0; margin-right:-12px;">
                        <div>
                            <ul class="uibutton-group">
                                <li><a class="uibutton normal" href="#" id="btnLogin" >Đăng nhập</a></li>
                                <li><a class="uibutton normal" href="#" id="forgetpass">quên mật khẩu</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            <input type="submit" name="update" value=" Apply "
                   style="position: absolute; height: 0px; width: 0px; border: none; padding: 0px;"
                   hidefocus="true" tabindex="-1"/>
            <?php $this->form->end()?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="shadow"></div>
</div>

<!--Login div-->
<div class="clear"></div>
<div id="versionBar">
    <div class="copyright"> © Copyright 2012  All Rights Reserved <span class="tip"><a href="http://xweb.vn" original-title="XWeb Việt Nam">XWeb VietNam</a> </span> </div>
    <!-- // copyright-->
</div>
<!-- Link JScript-->
<?php $this->html->loadJs(array("Content/XMin/js/jquery.min.js",
                                "Content/XMin/components/effect/jquery-jrumble.js",
                                "Content/XMin/components/ui/jquery.ui.min.js",
                                "Content/XMin/components/tipsy/jquery.tipsy.js",
                                "Content/XMin/components/checkboxes/iphone.check.js",
                                "Content/XMin/js/login.js"))?>
</body>
</html>