<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico  gray document"></span>Danh sách liên hệ</span> </div>
    <div class="content">
        <div class="load_page tableToolbar">
            <ul class="uibutton-group">
                <li><a class="uibutton special deleteAll" href="/en/Contact/ControlPanel/index">Liên hệ tiếng anh</a></li>
            </ul>
            <div class="tableName toolbar">
                <h3>Danh sách nội dung liên hệ</h3>
                <form id="tblForm" method="post" data-delete-url="<?php echo $this->url->action('delete')?>"
                      data-show-url="<?php echo $this->url->action('show')?>">
                    <table class="display" id="data_table" data-ajax-url="<?php echo $this->url->action('index')?>">
                        <thead>
                        <tr>
                            <th width="35">
                                <div class="checksquared"><input type="checkbox" id="checkAll1" class="checkAll" /><label for="checkAll1"></label></div>
                            </th>
                            <th width="100" align="left">Họ và tên</th>
                            <th width="100" align="left">Email</th>
                            <th width="100" align="left">Chủ đề</th>
                            <th width="100">Ngày đăng</th>
                            <th>Ngày đăng ẩn</th>
                            <th width="100">Số điện thoại</th>
                            <th width="100">Quản lý</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="dialog" style="display: none"></div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<?php $this->html->loadJs(array('Scripts/functions.js',
                                'Content/XMin/components/datatables/dataTables.min.js',
                                'Content/XMin/components/datatables/ColVis.js',
                                'Content/XMin/components/confirm/jquery.confirm.js',
                                'Application/Modules/Contact/Assets/js/index_controlpanel.js'))?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
<style type="text/css">
    .aleft{
        text-align: left;
    }
</style>
<?php $this->section->end()?>