<?php $this->content->begin() ?>
<div class="content projectContent">
    <div class="firstContent">
        <div class="blockTitle">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <a href="<?php echo $this->url->action('index','Index','Page') ?>">About Us</a> > <a href="<?php echo $this->url->action('category','Index','Image', array('page'=>1)) ?>">Gallery</a>
        </div>
        <div class="listProjects">
            <?php if(isset($albums[0])): ?>
            <div class="blockProject left first left-tablet">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[0]->id,'seo_url'=>$albums[0]->seo_url,'page'=>1)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[0]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[0]->id,'seo_url'=>$albums[0]->seo_url,'page'=>1)) ?>"><?php echo $albums[0]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[0]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[1])): ?>
            <div class="blockProject left">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[1]->id,'page'=>1,'seo_url'=>$albums[1]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[1]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[1]->id,'page'=>1,'seo_url'=>$albums[1]->seo_url)) ?>"><?php echo $albums[1]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[1]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[2])): ?>
            <div class="blockProject left left-tablet">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[2]->id,'page'=>1,'seo_url'=>$albums[2]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[2]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[2]->id,'page'=>1,'seo_url'=>$albums[2]->seo_url)) ?>"><?php echo $albums[2]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[2]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[3])): ?>
            <div class="blockProject">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[3]->id,'page'=>1,'seo_url'=>$albums[3]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[3]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[3]->id,'page'=>1,'seo_url'=>$albums[3]->seo_url)) ?>"><?php echo $albums[3]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[3]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[4])): ?>
            <div class="blockProject left left-tablet">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[4]->id,'page'=>1,'seo_url'=>$albums[4]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[4]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[4]->id,'page'=>1,'seo_url'=>$albums[4]->seo_url)) ?>"><?php echo $albums[4]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[4]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[5])): ?>
            <div class="blockProject left">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[5]->id,'page'=>1,'seo_url'=>$albums[5]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[5]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[5]->id,'page'=>1,'seo_url'=>$albums[5]->seo_url)) ?>"><?php echo $albums[5]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[5]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[6])): ?>
            <div class="blockProject left left-tablet">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[6]->id,'page'=>1,'seo_url'=>$albums[6]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[6]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[6]->id,'page'=>1,'seo_url'=>$albums[6]->seo_url)) ?>"><?php echo $albums[6]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[6]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <?php if(isset($albums[7])): ?>
            <div class="blockProject">
                <div class="blockImage"><a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[7]->id,'page'=>1,'seo_url'=>$albums[7]->seo_url)) ?>"><img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albums[7]->image) ?>&w=320&h=300&zc=1" /></a></div>
                <div class="blockContent">
                    <div class="projectTitle">
                        <a href="<?php echo $this->url->action('detail','Index','Image', array('id'=>$albums[7]->id,'page'=>1,'seo_url'=>$albums[7]->seo_url)) ?>"><?php echo $albums[7]->name ?></a>
                    </div>
                    <div class="projectInfo">
                        <?php echo $albums[7]->description ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <?php endif; ?>
            <div class="clearfix"></div>
        </div>
        <div class="controlBlock">
            <?php if($page > 1): ?>
            <a href="<?php echo $this->url->action('category','Index','Image', array('page'=>$page-1)) ?>" class="prev"><img src="<?php echo $this->url->content('/Content/VNCPC/images/prev.png') ?>" /></a>
            <?php endif; ?>
            <?php if(count($albums) == $limit ): ?>
            <a href="<?php echo $this->url->action('category','Index','Image', array('page'=>$page+1)) ?>" class="next"><img src="<?php echo $this->url->content('/Content/VNCPC/images/next.png') ?>" /></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php $this->content->end() ?>