<?php $this->content->begin() ?>
<script>
    $(document).ready(function(){
        //Examples of how to assign the Colorbox event to elements
        $(".group1").colorbox({rel:'group1'});      
    });
</script>
<div class="content gallryContent projectContent">
    <div class="firstContent">
        <div class="blockTitle">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <a href="<?php echo $this->url->action('index', 'Index', 'Page') ?>">Giới thiệu</a> > <a href="<?php echo $this->url->action('category', 'Index', 'Image', array('page' => 1)) ?>">Album Ảnh</a> ><a><?php echo $albumInfo->name; ?></a>
        </div>
        <div class="listProjects">
            <?php if (isset($albumImages[0])): ?>
                <div class="blockProject left first left-tablet">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[0]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[0]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[0]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[1])): ?>
                <div class="blockProject left">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[1]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[1]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[1]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[2])): ?>
                <div class="blockProject left left-tablet">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[2]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[2]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[2]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[3])): ?>
                <div class="blockProject">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[3]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[3]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[3]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[4])): ?>
                <div class="blockProject left left-tablet">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[4]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[4]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[4]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[5])): ?>
                <div class="blockProject left">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[5]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[5]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[5]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[6])): ?>
                <div class="blockProject left left-tablet">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[6]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[6]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[6]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <?php if (isset($albumImages[7])): ?>
                <div class="blockProject">
                    <div class="blockImage">
                        <a class="group1" href="<?php echo $albumImages[7]->file ?>">
                            <img src="/Thumb/phpThumb.php?src=<?php echo str_replace("http://vncpc.vn", "", $albumImages[7]->file) ?>&w=300&h=300&zc=1" />
                        </a>
                    </div>
                    <div class="blockContent">
                        <div class="projectTitle">
                            <a href="#"><?php echo $albumImages[7]->name ?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <?php endif; ?>
            <div class="clearfix"></div>
        </div>

        <div class="controlBlock">
            <?php if ($page > 1): ?>
                <a href="<?php echo $this->url->action('detail', 'Index', 'Image', array('id' => $albumInfo->id, 'seo_url' => $albumInfo->seo_url, 'page' => $page - 1)) ?>" class="prev"><img src="<?php echo $this->url->content('/Content/VNCPC/images/prev.png') ?>" /></a>
            <?php endif; ?>
            <?php if (count($albumImages) == $limit): ?>
                <a href="<?php echo $this->url->action('detail', 'Index', 'Image', array('id' => $albumInfo->id, 'seo_url' => $albumInfo->seo_url, 'page' => $page + 1)) ?>" class="next"><img src="<?php echo $this->url->content('/Content/VNCPC/images/next.png') ?>" /></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php $this->content->end() ?>
