<label for="value">Danh mục Video</label>
<div>
    <select id="value" name="value">
        <?php foreach($cats as $c):
            $url = $this->url->action('category', 'Index', 'Video', array('id' => $c->id));
        ?>
        <option data-url="<?php echo $url?>" value="<?php echo $c->id?>" <?php if($value == $c->id){?>selected="selected"<?php }?>><?php echo $c->name?></option>
        <?php endforeach?>
    </select>
    <label class="red" for="value">*</label>
</div>