<label for="value">Video</label>
<div>
    <select id="value" name="value">
        <?php foreach($articals as $a):
        $url = $this->url->action('detail','Index','Video',array('id'=> $id));
        ?>
        <option data-url="<?php echo $url?>" value="<?php echo $a->id?>" <?php if($value == $a->id){?>selected="selected"<?php }?>><?php echo $a->title?></option>
        <?php endforeach?>
    </select>
    <label class="red" for="value">*</label>
</div>