<?php
    function replaceSpace($str) {
        return str_replace(' ', '-', stripUnicode($str));
    }

    function stripUnicode($str){
        $str = preg_replace("/(à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ)/", 'a', $str);
        $str = preg_replace("/(è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ)/", 'e', $str);
        $str = preg_replace("/(ì|í|ị|ỉ|ĩ)/", 'i', $str);
        $str = preg_replace("/(ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ)/", 'o', $str);
        $str = preg_replace("/(ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ)/", 'u', $str);
        $str = preg_replace("/(ỳ|ý|ỵ|ỷ|ỹ)/", 'y', $str);
        $str = preg_replace("/(đ)/", 'd', $str);
        $str = preg_replace("/(À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ)/", 'A', $str);
        $str = preg_replace("/(È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ)/", 'E', $str);
        $str = preg_replace("/(Ì|Í|Ị|Ỉ|Ĩ)/", 'I', $str);
        $str = preg_replace("/(Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ)/", 'O', $str);
        $str = preg_replace("/(Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ)/", 'U', $str);
        $str = preg_replace("/(Ỳ|Ý|Ỵ|Ỷ|Ỹ)/", 'Y', $str);
        $str = preg_replace("/(Đ)/", 'D', $str);
//$str = str_replace(" ", "-", str_replace("&amp;*#39;","",$str));
        return $str;
    }
?>
<div class="linkList">
    <?php foreach($result_pag_data as $row):?>
        <a href="<?php echo $this->url->action("detail", "Index", "Project", array("id" => $row->id, "title" => $row->seo_url)); ?>"><?php echo $row->title?></a>
    <?php endforeach?>
</div>
<div class="pageNav">
    <!--    FOR ENABLING THE FIRST BUTTON-->

    <?php if ($first_btn):?>
        <a href="javascript:void(0);" p="1" class="prev"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/prev.png")?>" /></a>
    <?php endif;?>

    <!--    FOR ENABLING THE PREVIOUS BUTTON-->
    <!--    --><?php //if ($previous_btn && $cur_page > 1): ?>
    <!--        --><?php //$pre = $cur_page - 1;?>
    <!--        <a p='--><?php //echo $pre?><!--' class='active'>Previous</a>-->
    <!--    --><?php //elseif ($previous_btn):?>
    <!--        <a p='--><?php //echo $pre?><!--' class='inactive'>Previous</a>-->
    <!--    --><?php //endif;?>

    <?php for ($i = $start_loop; $i <= $end_loop; $i++) :?>

        <?php if ($cur_page == $i) :?>
            <a href="javascript:void(0);" p='<?php echo $i?>' class='current'><?php echo $i?></a>
        <?php else:?>
            <a href="javascript:void(0);" p='<?php echo $i?>'><?php echo $i?></a>
        <?php endif;?>
    <?php endfor;?>

    <!--    TO ENABLE THE NEXT BUTTON-->
    <!--    --><?php //if ($next_btn && $cur_page < $no_of_paginations):?>
    <!--        --><?php //$nex = $cur_page + 1;?>
    <!--        <a p='--><?php //echo $nex?><!--' class='active'>Next</a>-->
    <!--    --><?php //elseif($next_btn):?>
    <!--        <a p='--><?php //echo $nex?><!--' class='inactive'>Next</a>-->
    <!--    --><?php //endif;?>

    <!--    TO ENABLE THE END BUTTON-->

    <?php if ($last_btn):?>
        <a href="javascript:void(0);" p='<?php echo $no_of_paginations?>' class='next'><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/next.png")?>" /></a>
    <?php endif;?>
</div>
<div class="clearfix"></div>