<?php
/**
 * Created by JetBrains PhpStorm.
 * User: mc721
 * Date: 11/3/12
 * Time: 4:55 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>XWEB XAdmin - <?php echo $title?></title>
    <!-- Link shortcut icon-->
    <link rel="shortcut icon" type="image/ico" href="images/favicon2.ico" />
    <!-- Link css-->
    <?php $this->html->loadCss("Content/XMin/css/xmin.style.css")?>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lte IE 8]>
    <?php $this->html->loadJs('Content/XMin/components/flot/excanvas.min.js')?>
    <![endif]-->
</head>
<body class="dashborad">
<div id="alertMessage" class="error"></div>
<!-- Header -->
<div id="header">
    <div id="account_info">
        <img src="/Content/XMin/images/avatar.png" alt="Online" class="avatar" />
        <div class="setting">
            <b>Chào mừng,</b> <b class="red"><?php echo $this->session->teacher->username ?></b>
            <img src="/Content/XMin/images/gear.png" class="gear" alt="Cấu hình tài khoản" />
            <ul class="subnav ">
                <li><a href="<?php echo $this->url->action('index', 'Teacher', 'Dashboard')?>">Bảng điều khiển</a></li>
                <li><a href="<?php echo $this->url->action('edit', 'Teacher', 'User')?>/<?php echo $this->session->teacher->id ?>">Thông tin cá nhân</a></li>
                <!--<li><a href="#">Cấu hình</a></li>
                <li><a href="#">Reset mật khẩu</a></li> -->
                <br class="clear" />
            </ul>
        </div>
        <div class="logout" title="Ngắt kết nối" data-url="<?php echo $this->url->action('logout', 'Teacher', 'Auth')?>">
            <b>Đăng xuất</b>
            <img src="/Content/XMin/images/connect.png" name="connect" class="disconnect" alt="disconnect" />
        </div>
    </div>
</div><!-- End Header -->
<div id="shadowhead"></div>

<div id="left_menu">
    <?php 
        $this->html->renderAction('teacher', 'NavCom', 'Navigation');
    ?>
</div>


<div id="content">
    <div class="inner">
        <div class="topcolumn">
            <div class="logo"></div>
            <ul id="shortcut">
                <li><a href="#" title="Back To home"> <img src="/Content/XMin/images/icon/shortcut/home.png" alt="home" /><strong>Home</strong></a></li>
                <li><a href="#" title="Website Graph"> <img src="/Content/XMin/images/icon/shortcut/graph.png" alt="graph" /><strong>Graph</strong></a></li>
                <li><a href="#" title="Setting"> <img src="/Content/XMin/images/icon/shortcut/setting.png" alt="setting" /><strong>Setting</strong></a></li>
                <li><a href="#" title="Messages"> <img src="/Content/XMin/images/icon/shortcut/mail.png" alt="messages" /><strong>Message</strong></a><div class="notification">10</div></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
         <?php echo $this->content ?>
        <!-- clear fix -->
        <div class="clear"></div>
        <div id="footer"> &copy; Copyright 2012 <span class="tip"><a href="http://xweb.vn" title="XWeb Việt Nam">XWeb VietNam</a> </span> </div>
    </div> <!--// End inner -->
</div> <!--// End content -->
<?php $this->html->loadJs(array("Content/XMin/js/jquery.min.js",
                                "Content/XMin/components/ui/jquery.ui.min.js",
                                "Content/XMin/components/ui/jquery.autotab.js",
                                "Content/XMin/components/ui/timepicker.js",
                                "Content/XMin/components/checkboxes/iphone.check.js",
                                "Content/XMin/components/scrolltop/scrolltopcontrol.js",
                                "Content/XMin/components/flot/flot.js",
                                "Content/XMin/components/flot/flot.pie.min.js",
                                "Content/XMin/components/flot/flot.resize.min.js",
                                "Content/XMin/components/flot/graphtable.js",
                                "Content/XMin/components/checkboxes/customInput.jquery.js",
                                "Content/XMin/components/effect/jquery-jrumble.js",
                                "Content/XMin/components/imgTransform/jquery.transform.js",
                                "Content/XMin/components/tipsy/jquery.tipsy.js",
                                "Content/XMin/components/placeholder/jquery.placeholder.js",
                                "Content/XMin/components/fancybox/jquery.fancybox.js",
                                "Content/XMin/js/jquery.cookie.js",
                                "Content/XMin/js/xmin.custom.js"
))?>
<!--
<script type="text/javascript" src="components/colorpicker/js/colorpicker.js"></script>
<script type="text/javascript" src="components/elfinder/js/elfinder.full.js"></script>
<script type="text/javascript" src="components/datatables/dataTables.min.js"></script>
<script type="text/javascript" src="components/datatables/ColVis.js"></script>
<script type="text/javascript" src="components/jscrollpane/mousewheel.js"></script>
<script type="text/javascript" src="components/jscrollpane/mwheelIntent.js"></script>
<script type="text/javascript" src="components/jscrollpane/jscrollpane.min.js"></script>
<script type="text/javascript" src="components/spinner/ui.spinner.js"></script>
<script type="text/javascript" src="components/editor/jquery.cleditor.js"></script>
<script type="text/javascript" src="components/chosen/chosen.js"></script>
<script type="text/javascript" src="components/confirm/jquery.confirm.js"></script>
<script type="text/javascript" src="components/validationEngine/jquery.validationEngine.js"></script>
<script type="text/javascript" src="components/validationEngine/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="components/vticker/jquery.vticker-min.js"></script>
<script type="text/javascript" src="components/sourcerer/sourcerer.js"></script>
<script type="text/javascript" src="components/fullcalendar/fullcalendar.js"></script>
<script type="text/javascript" src="components/uploadify/swfobject.js"></script>
<script type="text/javascript" src="components/uploadify/uploadify.js"></script>
<script type="text/javascript" src="components/filestyle/jquery.filestyle.js"></script>
<script type="text/javascript" src="components/Jcrop/jquery.Jcrop.js"></script>
<script type="text/javascript" src="components/webcam/webcam.js"></script>
<script type="text/javascript" src="components/rating_star/rating_star.js"></script>
<script type="text/javascript" src="components/dualListBox/dualListBox.js"></script>
<script type="text/javascript" src="components/smartWizard/jquery.smartWizard.min.js"></script>
<script type="text/javascript" src="components/maskedinput/jquery.maskedinput.js"></script>
<script type="text/javascript" src="components/highlightText/highlightText.js"></script>
<script type="text/javascript" src="components/elastic/jquery.elastic.source.js"></script>
-->
<?php echo $this->section->scripts?>
<?php echo $this->section->stylesheets?>
</body>
</html>