<?php $this->content->begin() ?>
<div class="content aboutContent">

    <div class="secondContent">
        <div class="blockNav first">
            <div class="blockTitle"><a href="#">Lịch Sử<br />Phát Triển</a></div><div class="clearfix"></div>
            <div class="blockIcon"><img src="/Content/VNCPC/images/icons/block-nav-icon1.png"/></div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNav left">
            <div class="blockTitle"><a href="#">Tầm nhìn<br />sứ mệnh</a></div><div class="clearfix"></div>
            <div class="blockIcon"><img src="/Content/VNCPC/images/icons/block-nav-icon2.png"/></div>
            <div class="clearfix"></div>
        </div>

        <div class="blockNav left-phone">
            <div class="blockTitle"><a href="#">Cán Bộ</a></div><div class="clearfix"></div>
            <div class="blockIcon"><img src="/Content/VNCPC/images/icons/block-nav-icon3.png"/></div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNav left">
            <div class="blockTitle"><a href="#">Sơ Đồ<br />Tổ Chức</a></div><div class="clearfix"></div>
            <div class="blockIcon"><img src="/Content/VNCPC/images/icons/block-nav-icon4.png"/></div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNav last">
            <div class="blockTitle"><a href="#">Các <br />Đối tác</a></div><div class="clearfix"></div>
            <div class="blockIcon"><img src="/Content/VNCPC/images/icons/block-nav-icon5.png"/></div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="firstContent">
        <div class="blockTitle"><a href="#">Giới Thiệu</a> > <a href="#">Lịch Sử Phát Triển</a></div>
        <div class="blockContent">
            <div class="blockContentImage">
                <img src="/Content/VNCPC/images/contents/image-gallery.png" />
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>
                <p class="Normal"><font color="#0f0f0f">"Cách làm vô cùng đơn giản mà không ảnh hưởng nhiều đến kết cấu công trình, đó là cưa chỗ khớp nối giữa đầu và cổ rồng, sau đó nối thêm khoảng 2 m ống thép và gắn lại. Đầu rồng cao nhìn sẽ đẹp hơn hiện tại rất nhiều", ông Hà nói và cho biết về kỹ thuật, khi nối các ống thép phải trùng nhau 10 cm và gắn chặt lại để đảm bảo an toàn.</font></p>

            </div>
            <div class="pageControl">
                <div class="topControl">
                    Số Lượt Đọc: <strong>37708</strong> - Cập nhật lần cuối: <strong>29/01/2008 10:50:06 PM</strong>
                </div>
                <div class="bottomControl">
                    <a href="#"><img src="/Content/VNCPC/images/icons/back.png">Về trang trước</a>
                    <a href="#"><img src="/Content/VNCPC/images/icons/print.png">Bản in</a>
                    <a href="#"><img src="/Content/VNCPC/images/icons/mail.png">Gửi mail</a>
                    <a href="#"><img src="/Content/VNCPC/images/icons/totop.png">Về đầu trang</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="partnerLink">
        <div class="contentPartnerLink">
            <div class="partnerLinkTitle">
                <span>Liên kết đối tác</span>
            </div>
            <div class="linkList">
                <a href="#"><img src="/Content/VNCPC/images/contents/partner-link1.png"/></a>
                <a href="#"><img src="/Content/VNCPC/images/contents/partner-link2.png"/></a>
                <a href="#"><img src="/Content/VNCPC/images/contents/partner-link3.png"/></a>
                <a href="#"><img src="/Content/VNCPC/images/contents/partner-link4.png"/></a>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

<div class="clearfix"></div>
<?php $this->content->end() ?>