<?php $this->content->begin() ?>
<style>
/*-----------------------contact_form-------------------*/
.form{
width:500px;
height:auto;
float:left;
padding:20px 10px 10px 20px;
border:1px #fdeaeb solid;
}
.form_row{
width:425px;
float:left;
clear:both;
padding:7px 0 7px 0;
}
label{
width:100px;
float:left;
padding:3px 15px 0 0;
color:#b52025;
text-align:right;
font-size: 13px;
font-weight:bold;
}
input.main_input{
background-color:#fdeaeb;
border:1px #e2c7c8 solid;
width:300px;
height:18px;
padding:4px;
float:left;
}
textarea.main_textarea{
background-color:#fdeaeb;
border:1px #e2c7c8 solid;
width:300px;
height:120px;
padding:4px;
float:left;
}
input.submit{
background-color:#b52025;
color:#FFFFFF;
text-align:center;
float:right;
padding:3px 10px 2px 10px;
margin:0px 0 0 0;
border:1px #b52025 solid;
cursor:pointer;
}
</style>
<div class="main-content">
    <h4>Liên hệ với chúng tôi</h4>
    <form action="<?php echo $this->url->action('contact','Index','') ?>" id="contact" name="contact" method="post">
        <div class="form">
            <div class="form_row">
                <label>Tên:</label>
                <input type="text" id="name" name="name" class="main_input">
            </div>

            <div class="form_row">
                <label>Email:</label>
                <input type="text" id="email" name="email" class="main_input">
            </div> 

            <div class="form_row">
                <label>Số điện thoại:</label>
                <input type="text" id="phone" name="phone" class="main_input">
            </div> 

            <div class="form_row">
                <label> Địa chỉ:</label>
                <input type="text" id="address" name="address" class="main_input">
            </div>

            <div class="form_row">
                <label>Lời nhắn:</label>
                <textarea id="message" name="message" class="main_textarea"></textarea>
            </div> 

            <div class="form_row">
                <input type="submit" name="submit" class="submit" value="Gửi Liên Hệ">
            </div>

        </div>
    </form>

</div>

<div class="sidebar">
    <div class="news-panel">
        <a class="title">Tin tức</a>
        <div class="cnt">
            <ul>
                <?php foreach($news as $new): ?>
                <li>
                    <div class="news-item">
                        <a href="<?php echo $this->url->action('index','Index','Artical', array('seo_url'=> $new->seo_url,'id'=>$new->id)) ?>" class="n-title"><?php echo $new->title ?></a>
                        <p class="n-date"><?php echo date('d-m-Y', strtotime($new->created_date)) ?></p>
                    </div>
                </li>       
                <?php endforeach; ?>
            </ul>
            <a href="<?php echo $this->url->action('category','Index','Artical', array('seo_url'=> 'tin-tuc','id'=>2)) ?>" class="news-more">Các tin khác</a>
        </div>
    </div>
</div>
<div class="cl"></div>
<div class="main-intro">
<?php $this->content->end() ?>