<?php $this->content->begin() ?>
<div class="content newsContent">
    <div class="firstContent">
        <div class="blockNews groupThree left">
            <div class="blockTitle"><a href="#">Tin Mới Nhất</a></div>
            <div class="newsGroup">
                <div class="newsItem first">
                    <img src="images/contents/news1.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="newsItem">
                    <img src="images/contents/news2.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="newsItem last">
                    <img src="images/contents/news1.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNews">
            <div class="blockTitle"><a href="#">Tin Từ trung tâm</a></div>
            <div class="newsItem">
                <img src="images/contents/news3.png" />
                <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNews left">
            <div class="blockTitle"><a href="#">Tin từ các dự án</a></div>
            <div class="newsItem">
                <img src="images/contents/news3.png" />
                <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blockNews groupThree">
            <div class="blockTitle"><a href="#">tin về sản xuất và tiêu thụ bền vững</a></div>
            <div class="newsGroup">
                <div class="newsItem first">
                    <img src="images/contents/news1.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="newsItem">
                    <img src="images/contents/news2.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="newsItem last">
                    <img src="images/contents/news1.png" />
                    <div class="newsTitle"><a href="#">Sản xuất sạch hơn giúp làng nghề phát triển bền vững ( 29 thg 1, 2013)</a></div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
    <div class="partnerLink">
        <div class="contentPartnerLink">
            <div class="partnerLinkTitle">
                <span>Liên kết đối tác</span>
            </div>
            <div class="linkList">
                <a href="#"><img src="images/contents/partner-link1.png"/></a>
                <a href="#"><img src="images/contents/partner-link2.png"/></a>
                <a href="#"><img src="images/contents/partner-link3.png"/></a>
                <a href="#"><img src="images/contents/partner-link4.png"/></a>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php $this->content->end() ?>