<?php $this->content->begin()?>

    <?php
        $first = 0;
        $last = count($articals);
        $first_artical = $articals[0];
        function getClass($first, $last) {
            if($first == 1) return "first";
            elseif($first == $last) return "last";
            elseif($first % 2 == 0) return "left";
            else return "left-phone";
        }
    ?>

        <?php $this->html->renderAction('index','BlockCom','Block', array('left service')) ?>

        <div class="firstContent">
            <div id="content">
                <div class="blockTitle"><a href="<?php echo $this->url->action("index", "Index", "Service")?>">Services</a> > <a href="#"><?php echo $first_artical->title; ?></a></div>
                <div class="blockContent">
                    <div class="blockContentImage" id="print">
                        <?php echo $first_artical->content;?>
                    </div>
                    <div class="pageControl">
                        <div class="topControl">
                            View Number : <strong><?php echo $first_artical->view_count +1;?></strong> - Last time updated: <strong>06/08/2013 10:50:06 AM</strong>
                        </div>
                        <div class="bottomControl">
                            <a href="javascript:history.go(-1)"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/back.png")?>">Back previous page</a>
                            <a href="#" onClick="printF('print')"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/print.png")?>">Print</a>
                            <a href="<?php echo $this->url->action("index", "Index", "Contact")?>"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/mail.png")?>">Email us</a>
                            <a href="#"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/totop.png")?>">Top</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>





    <script>
        /*$(document).ready(function(){
            $('#load').click(function(){
                $("#content").load("/Page/Index/test");
            });
        });*/
        function loadArtical(id) {
            $("#content").load("<?php echo $this->url->action('load', 'Index', 'Service');?>"+ '/' + id);
            return false;
        }

        $(document).ready(function(){
             //$('#menuAbout').addClass("active");
             $('#wrapper').addClass("aboutPage");
             $('.content').addClass("aboutContent");
         });
    </script>

<?php $this->content->end()?>