<div class="blockTitle"><a href="<?php echo $this->url->action("index", "Index", "Service")?>">Services</a> > <a href="#"><?php echo $artical->title; ?></a></div>
<div class="blockContent">
    <div class="blockContentImage" id="print">
        <?php echo $artical->content;?>
    </div>
    <div class="pageControl">
        <div class="topControl">
            View Number : <strong><?php echo $artical->view_count +1;?></strong> - Last time updated: <strong>06/08/2013 10:50:06 AM</strong>
        </div>
        <div class="bottomControl">
            <a href="javascript:history.go(-1)"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/back.png")?>">Back previous page</a>
            <a href="#" onClick="printF('print')"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/print.png")?>">Print</a>
            <a href="<?php echo $this->url->action("index", "Index", "Contact")?>"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/mail.png")?>">Email us</a>
            <a href="#"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/totop.png")?>">Top</a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>