<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico  gray document"></span>Bài viết</span> </div>
    <div class="content">
        <div class="load_page tableToolbar">
            <ul class="uibutton-group">
                <li><a class="uibutton icon add" title="Add Product" href="<?php echo $this->url->action('createImage', array($catId))?>">Thêm bài viết mới</a></li>
                <li><a class="uibutton special deleteAll">Xoá</a></li>
            </ul>
            <div class="tableName toolbar">
                <form id="tblForm" method="post" data-delete-url="<?php echo $this->url->action('deleteImage')?>"
                                                 data-edit-url="<?php echo $this->url->action('editImage')?>">
                    <?php $this->form->select('catFilter', $categoryOptions, NULL, NULL, NULL, array('class' => 'selectBox medium cat_filter_wrp'))?>
                    <table class="display" id="data_table" data-ajax-url="<?php echo $this->url->action('view')?>">
                        <thead>
                        <tr>
                            <th width="35">
                                <div class="checksquared"><input type="checkbox" id="checkAll1" class="checkAll" /><label for="checkAll1"></label></div>
                            </th>                            
                            <th width="300" align="left">Album</th>
                            <th width="150">Ảnh</th>
                            <th width="300" align="left">Tên</th>
                            <th width="100">Quản lý</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<script type="text/javascript">
    $(function(){
    <?php if($catDefault):?>
        $('#catFilter').val('<?php echo $catDefault?>');
        $('#catFilter').selectBox();
        <?php endif?>
    });
</script>
<?php $this->html->loadJs(array('Scripts/functions.js',
                                'Content/XMin/components/datatables/dataTables.min.js',
                                'Content/XMin/components/datatables/ColVis.js',
                                'Content/XMin/components/datatables/jquery.dataTables.columnFilter.js',
                                'Content/XMin/components/confirm/jquery.confirm.js',
                                'Application/Modules/Image/Assets/js/index_view.js'))?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
    <style type="text/css">
        .aleft{
            text-align: left;
        }
    </style>
<?php $this->section->end()?>