// jQuery Plugins: jEmotion 2.3
// Copyright @ www.phpbasic.com
// View http://jquery.phpbasic.com/jemotion for new version

(function($) {
	$.fn.emotion = function(settings,more_emotions) {
		var _cfg = {
			handle: 'a.emotion-toggle',
			dir: 'Content/Emotions/',
			label: 'Click here to show emotion icons',
			style: null,
			cls: null,
			r_alert: 1,
			emotions: [
/********** LIKE YAHOO **************/
{syntax: '&gt;:)',title: 'devil',icon: '1.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':((',title: 'crying',icon: '2.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ';;)',title: 'batting eyelashes',icon: '3.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '&gt;:D&lt;',title: 'big hug',icon: '4.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '&lt;):)',title: 'cowboy',icon: '5.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':D',title: 'big grin',icon: '6.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-/',title: 'confused',icon: '7.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':x',title: 'love struck',icon: '8.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '&gt;:P',title: 'phbbbbt',icon: '10.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-*',title: 'kiss',icon: '11.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '=((',title: 'broken heart',icon: '12.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-O',title: 'surprise',icon: '13.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '~X(',title: 'at wits\' end',icon: '14.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':&gt;',title: 'smug',icon: '15.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: 'B-)',title: 'cool',icon: '16.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-SS',title: 'nail biting',icon: '17.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '#:-S',title: 'whew!',icon: '18.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':))',title: 'laughing',icon: '19.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':(',title: 'sad',icon: '20.gif'},
{syntax: '/:)',title: 'raised eyebrows',icon:'21.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '(:|',title: 'yawn',icon: '22.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':)]',title: 'on the phone',icon: '23.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '=))',title: 'rolling on the floor',icon: '24.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: 'O:-)',title: 'angel',icon: '25.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-B',title: 'nerd',icon: '26.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '=;',title: 'talk to the hand',icon: '27.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '8-|',title: 'rolling eyes',icon: '29.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: 'L-)',title: 'loser',icon: '30.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-&amp;',title: 'sick',icon: '31.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-$',title: 'don\'t tell anyone',icon: '32.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '[-(',title: 'no talking',icon: '33.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':O)',title: 'clown',icon: '34.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '8-}',title: 'silly',icon: '35.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '&lt;:-P',title: 'party',icon: '36.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':|',title: 'straight face',icon: '37.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '=P~',title: 'drooling',icon: '38.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-?',title: 'thinking',icon: '39.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '#-o',title: 'd\'oh',icon: '40.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '=D&gt;',title: 'applause',icon: '41.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-S',title: 'worried',icon: '42.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '@-)',title: 'hypnotized',icon: '43.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':^o',title: 'liar',icon: '44.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-w',title: 'waiting',icon: '45.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-&lt;',title: 'sigh',icon: '46.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':P',title: 'tongue',icon: '47.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ';)',title: 'winking',icon: '48.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':)',title: 'happy',icon: '100.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-c',title: 'call me',icon: '101.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: 'X(',title: 'angry',icon: '102.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: ':-h',title: 'wave',icon: '103.gif',group: 'yahoo', group_name: 'Thường dùng'},
{syntax: '8-&gt;',title: 'day dreaming',icon: '105.gif',group: 'yahoo', group_name: 'Thường dùng'},

/**************** BABY ****************/
{"syntax":"(bb)10","title":"baby","icon":"10.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)11","title":"baby","icon":"11.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)12","title":"baby","icon":"12.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)13","title":"baby","icon":"13.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)14","title":"baby","icon":"14.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)15","title":"baby","icon":"15.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)16","title":"baby","icon":"16.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)17","title":"baby","icon":"17.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)18","title":"baby","icon":"18.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)19","title":"baby","icon":"19.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)20","title":"baby","icon":"20.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)21","title":"baby","icon":"21.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)22","title":"baby","icon":"22.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)23","title":"baby","icon":"23.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)24","title":"baby","icon":"24.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)25","title":"baby","icon":"25.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)26","title":"baby","icon":"26.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)27","title":"baby","icon":"27.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)28","title":"baby","icon":"28.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)29","title":"baby","icon":"29.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)30","title":"baby","icon":"30.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)31","title":"baby","icon":"31.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)32","title":"baby","icon":"32.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)33","title":"baby","icon":"33.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)34","title":"baby","icon":"34.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)35","title":"baby","icon":"35.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)36","title":"baby","icon":"36.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)37","title":"baby","icon":"37.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)38","title":"baby","icon":"38.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)39","title":"baby","icon":"39.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)40","title":"baby","icon":"40.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)41","title":"baby","icon":"41.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)42","title":"baby","icon":"42.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)43","title":"baby","icon":"43.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)44","title":"baby","icon":"44.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)45","title":"baby","icon":"45.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)46","title":"baby","icon":"46.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)47","title":"baby","icon":"47.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)48","title":"baby","icon":"48.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)49","title":"baby","icon":"49.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)50","title":"baby","icon":"50.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)51","title":"baby","icon":"51.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)52","title":"baby","icon":"52.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)53","title":"baby","icon":"53.gif","group":"baby","group_name":"Baby"},
{"syntax":"(bb)54","title":"baby","icon":"54.gif","group":"baby","group_name":"Baby"},

/**************** RED FOX ****************/
{"syntax":"(gb)1","title":"bagiaxanh","icon":"1.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)10","title":"bagiaxanh","icon":"10.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)11","title":"bagiaxanh","icon":"11.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)12","title":"bagiaxanh","icon":"12.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)13","title":"bagiaxanh","icon":"13.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)14","title":"bagiaxanh","icon":"14.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)15","title":"bagiaxanh","icon":"15.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)16","title":"bagiaxanh","icon":"16.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)17","title":"bagiaxanh","icon":"17.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)18","title":"bagiaxanh","icon":"18.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)19","title":"bagiaxanh","icon":"19.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)2","title":"bagiaxanh","icon":"2.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)20","title":"bagiaxanh","icon":"20.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)21","title":"bagiaxanh","icon":"21.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)22","title":"bagiaxanh","icon":"22.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)23","title":"bagiaxanh","icon":"23.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)24","title":"bagiaxanh","icon":"24.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)25","title":"bagiaxanh","icon":"25.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)26","title":"bagiaxanh","icon":"26.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)27","title":"bagiaxanh","icon":"27.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)28","title":"bagiaxanh","icon":"28.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)29","title":"bagiaxanh","icon":"29.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)3","title":"bagiaxanh","icon":"3.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)30","title":"bagiaxanh","icon":"30.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)31","title":"bagiaxanh","icon":"31.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)32","title":"bagiaxanh","icon":"32.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)33","title":"bagiaxanh","icon":"33.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)34","title":"bagiaxanh","icon":"34.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)35","title":"bagiaxanh","icon":"35.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)36","title":"bagiaxanh","icon":"36.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)37","title":"bagiaxanh","icon":"37.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)38","title":"bagiaxanh","icon":"38.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)39","title":"bagiaxanh","icon":"39.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)4","title":"bagiaxanh","icon":"4.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)40","title":"bagiaxanh","icon":"40.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)41","title":"bagiaxanh","icon":"41.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)42","title":"bagiaxanh","icon":"42.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)43","title":"bagiaxanh","icon":"43.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)44","title":"bagiaxanh","icon":"44.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)45","title":"bagiaxanh","icon":"45.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)46","title":"bagiaxanh","icon":"46.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)47","title":"bagiaxanh","icon":"47.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)48","title":"bagiaxanh","icon":"48.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)49","title":"bagiaxanh","icon":"49.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)5","title":"bagiaxanh","icon":"5.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)50","title":"bagiaxanh","icon":"50.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)51","title":"bagiaxanh","icon":"51.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)52","title":"bagiaxanh","icon":"52.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)53","title":"bagiaxanh","icon":"53.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)54","title":"bagiaxanh","icon":"54.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)55","title":"bagiaxanh","icon":"55.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)56","title":"bagiaxanh","icon":"56.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)57","title":"bagiaxanh","icon":"57.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)6","title":"bagiaxanh","icon":"6.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)7","title":"bagiaxanh","icon":"7.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)8","title":"bagiaxanh","icon":"8.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},
{"syntax":"(gb)9","title":"bagiaxanh","icon":"9.gif","group":"bagiaxanh","group_name":"B\u00e0 gi\u00e0 xanh"},


{"syntax":"(bo)1","title":"binhsua","icon":"1.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)10","title":"binhsua","icon":"10.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)100","title":"binhsua","icon":"100.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)101","title":"binhsua","icon":"101.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)102","title":"binhsua","icon":"102.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)103","title":"binhsua","icon":"103.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)104","title":"binhsua","icon":"104.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)105","title":"binhsua","icon":"105.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)106","title":"binhsua","icon":"106.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)107","title":"binhsua","icon":"107.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)108","title":"binhsua","icon":"108.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)109","title":"binhsua","icon":"109.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)11","title":"binhsua","icon":"11.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)110","title":"binhsua","icon":"110.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)111","title":"binhsua","icon":"111.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)112","title":"binhsua","icon":"112.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)113","title":"binhsua","icon":"113.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)114","title":"binhsua","icon":"114.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)115","title":"binhsua","icon":"115.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)116","title":"binhsua","icon":"116.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)117","title":"binhsua","icon":"117.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)118","title":"binhsua","icon":"118.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)119","title":"binhsua","icon":"119.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)12","title":"binhsua","icon":"12.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)120","title":"binhsua","icon":"120.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)121","title":"binhsua","icon":"121.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)122","title":"binhsua","icon":"122.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)123","title":"binhsua","icon":"123.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)124","title":"binhsua","icon":"124.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)125","title":"binhsua","icon":"125.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)126","title":"binhsua","icon":"126.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)127","title":"binhsua","icon":"127.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)128","title":"binhsua","icon":"128.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)129","title":"binhsua","icon":"129.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)13","title":"binhsua","icon":"13.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)130","title":"binhsua","icon":"130.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)131","title":"binhsua","icon":"131.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)132","title":"binhsua","icon":"132.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)133","title":"binhsua","icon":"133.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)134","title":"binhsua","icon":"134.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)135","title":"binhsua","icon":"135.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)136","title":"binhsua","icon":"136.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)137","title":"binhsua","icon":"137.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)138","title":"binhsua","icon":"138.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)139","title":"binhsua","icon":"139.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)14","title":"binhsua","icon":"14.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)140","title":"binhsua","icon":"140.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)141","title":"binhsua","icon":"141.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)142","title":"binhsua","icon":"142.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)143","title":"binhsua","icon":"143.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)144","title":"binhsua","icon":"144.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)145","title":"binhsua","icon":"145.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)146","title":"binhsua","icon":"146.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)147","title":"binhsua","icon":"147.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)148","title":"binhsua","icon":"148.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)149","title":"binhsua","icon":"149.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)15","title":"binhsua","icon":"15.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)150","title":"binhsua","icon":"150.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)151","title":"binhsua","icon":"151.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)152","title":"binhsua","icon":"152.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)153","title":"binhsua","icon":"153.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)154","title":"binhsua","icon":"154.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)155","title":"binhsua","icon":"155.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)156","title":"binhsua","icon":"156.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)157","title":"binhsua","icon":"157.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)158","title":"binhsua","icon":"158.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)159","title":"binhsua","icon":"159.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)16","title":"binhsua","icon":"16.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)160","title":"binhsua","icon":"160.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)161","title":"binhsua","icon":"161.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)162","title":"binhsua","icon":"162.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)163","title":"binhsua","icon":"163.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)164","title":"binhsua","icon":"164.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)165","title":"binhsua","icon":"165.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)166","title":"binhsua","icon":"166.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)167","title":"binhsua","icon":"167.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)168","title":"binhsua","icon":"168.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)169","title":"binhsua","icon":"169.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)17","title":"binhsua","icon":"17.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)170","title":"binhsua","icon":"170.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)171","title":"binhsua","icon":"171.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)172","title":"binhsua","icon":"172.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)173","title":"binhsua","icon":"173.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)18","title":"binhsua","icon":"18.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)19","title":"binhsua","icon":"19.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)2","title":"binhsua","icon":"2.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)20","title":"binhsua","icon":"20.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)21","title":"binhsua","icon":"21.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)22","title":"binhsua","icon":"22.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)23","title":"binhsua","icon":"23.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)24","title":"binhsua","icon":"24.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)25","title":"binhsua","icon":"25.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)26","title":"binhsua","icon":"26.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)27","title":"binhsua","icon":"27.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)28","title":"binhsua","icon":"28.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)29","title":"binhsua","icon":"29.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)3","title":"binhsua","icon":"3.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)30","title":"binhsua","icon":"30.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)31","title":"binhsua","icon":"31.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)32","title":"binhsua","icon":"32.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)33","title":"binhsua","icon":"33.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)34","title":"binhsua","icon":"34.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)35","title":"binhsua","icon":"35.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)36","title":"binhsua","icon":"36.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)37","title":"binhsua","icon":"37.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)38","title":"binhsua","icon":"38.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)39","title":"binhsua","icon":"39.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)4","title":"binhsua","icon":"4.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)40","title":"binhsua","icon":"40.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)41","title":"binhsua","icon":"41.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)42","title":"binhsua","icon":"42.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)43","title":"binhsua","icon":"43.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)44","title":"binhsua","icon":"44.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)45","title":"binhsua","icon":"45.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)46","title":"binhsua","icon":"46.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)47","title":"binhsua","icon":"47.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)48","title":"binhsua","icon":"48.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)49","title":"binhsua","icon":"49.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)5","title":"binhsua","icon":"5.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)50","title":"binhsua","icon":"50.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)51","title":"binhsua","icon":"51.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)52","title":"binhsua","icon":"52.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)53","title":"binhsua","icon":"53.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)54","title":"binhsua","icon":"54.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)55","title":"binhsua","icon":"55.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)56","title":"binhsua","icon":"56.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)57","title":"binhsua","icon":"57.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)58","title":"binhsua","icon":"58.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)59","title":"binhsua","icon":"59.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)6","title":"binhsua","icon":"6.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)60","title":"binhsua","icon":"60.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)61","title":"binhsua","icon":"61.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)62","title":"binhsua","icon":"62.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)63","title":"binhsua","icon":"63.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)64","title":"binhsua","icon":"64.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)65","title":"binhsua","icon":"65.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)66","title":"binhsua","icon":"66.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)67","title":"binhsua","icon":"67.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)68","title":"binhsua","icon":"68.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)69","title":"binhsua","icon":"69.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)7","title":"binhsua","icon":"7.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)70","title":"binhsua","icon":"70.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)71","title":"binhsua","icon":"71.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)72","title":"binhsua","icon":"72.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)73","title":"binhsua","icon":"73.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)74","title":"binhsua","icon":"74.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)75","title":"binhsua","icon":"75.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)76","title":"binhsua","icon":"76.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)77","title":"binhsua","icon":"77.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)78","title":"binhsua","icon":"78.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)79","title":"binhsua","icon":"79.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)8","title":"binhsua","icon":"8.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)80","title":"binhsua","icon":"80.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)81","title":"binhsua","icon":"81.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)82","title":"binhsua","icon":"82.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)83","title":"binhsua","icon":"83.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)84","title":"binhsua","icon":"84.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)85","title":"binhsua","icon":"85.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)86","title":"binhsua","icon":"86.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)87","title":"binhsua","icon":"87.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)88","title":"binhsua","icon":"88.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)89","title":"binhsua","icon":"89.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)9","title":"binhsua","icon":"9.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)90","title":"binhsua","icon":"90.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)91","title":"binhsua","icon":"91.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)92","title":"binhsua","icon":"92.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)93","title":"binhsua","icon":"93.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)94","title":"binhsua","icon":"94.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)95","title":"binhsua","icon":"95.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)96","title":"binhsua","icon":"96.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)97","title":"binhsua","icon":"97.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)98","title":"binhsua","icon":"98.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},
{"syntax":"(bo)99","title":"binhsua","icon":"99.gif","group":"binhsua","group_name":"B\u00ecnh s\u1eefa"},


{"syntax":"(gf)1","title":"echxanh","icon":"1.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)10","title":"echxanh","icon":"10.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)11","title":"echxanh","icon":"11.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)12","title":"echxanh","icon":"12.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)13","title":"echxanh","icon":"13.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)14","title":"echxanh","icon":"14.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)15","title":"echxanh","icon":"15.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)16","title":"echxanh","icon":"16.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)17","title":"echxanh","icon":"17.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)18","title":"echxanh","icon":"18.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)19","title":"echxanh","icon":"19.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)2","title":"echxanh","icon":"2.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)20","title":"echxanh","icon":"20.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)21","title":"echxanh","icon":"21.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)22","title":"echxanh","icon":"22.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)23","title":"echxanh","icon":"23.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)24","title":"echxanh","icon":"24.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)25","title":"echxanh","icon":"25.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)26","title":"echxanh","icon":"26.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)27","title":"echxanh","icon":"27.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)28","title":"echxanh","icon":"28.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)29","title":"echxanh","icon":"29.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)3","title":"echxanh","icon":"3.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)30","title":"echxanh","icon":"30.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)31","title":"echxanh","icon":"31.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)32","title":"echxanh","icon":"32.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)33","title":"echxanh","icon":"33.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)34","title":"echxanh","icon":"34.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)35","title":"echxanh","icon":"35.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)36","title":"echxanh","icon":"36.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)37","title":"echxanh","icon":"37.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)38","title":"echxanh","icon":"38.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)39","title":"echxanh","icon":"39.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)4","title":"echxanh","icon":"4.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)40","title":"echxanh","icon":"40.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)41","title":"echxanh","icon":"41.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)42","title":"echxanh","icon":"42.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)43","title":"echxanh","icon":"43.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)44","title":"echxanh","icon":"44.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)45","title":"echxanh","icon":"45.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)46","title":"echxanh","icon":"46.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)47","title":"echxanh","icon":"47.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)48","title":"echxanh","icon":"48.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)49","title":"echxanh","icon":"49.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)5","title":"echxanh","icon":"5.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)50","title":"echxanh","icon":"50.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)51","title":"echxanh","icon":"51.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)52","title":"echxanh","icon":"52.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)53","title":"echxanh","icon":"53.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)54","title":"echxanh","icon":"54.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)55","title":"echxanh","icon":"55.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)56","title":"echxanh","icon":"56.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)57","title":"echxanh","icon":"57.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)58","title":"echxanh","icon":"58.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)59","title":"echxanh","icon":"59.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)6","title":"echxanh","icon":"6.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)60","title":"echxanh","icon":"60.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)61","title":"echxanh","icon":"61.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)62","title":"echxanh","icon":"62.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)63","title":"echxanh","icon":"63.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)64","title":"echxanh","icon":"64.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)65","title":"echxanh","icon":"65.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)66","title":"echxanh","icon":"66.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)67","title":"echxanh","icon":"67.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)68","title":"echxanh","icon":"68.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)69","title":"echxanh","icon":"69.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)7","title":"echxanh","icon":"7.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)70","title":"echxanh","icon":"70.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)71","title":"echxanh","icon":"71.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)72","title":"echxanh","icon":"72.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)73","title":"echxanh","icon":"73.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)74","title":"echxanh","icon":"74.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)75","title":"echxanh","icon":"75.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)76","title":"echxanh","icon":"76.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)77","title":"echxanh","icon":"77.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)78","title":"echxanh","icon":"78.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)79","title":"echxanh","icon":"79.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)8","title":"echxanh","icon":"8.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)80","title":"echxanh","icon":"80.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)81","title":"echxanh","icon":"81.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)82","title":"echxanh","icon":"82.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)83","title":"echxanh","icon":"83.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)84","title":"echxanh","icon":"84.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)85","title":"echxanh","icon":"85.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)86","title":"echxanh","icon":"86.gif","group":"echxanh","group_name":"\u1ebech xanh"},
{"syntax":"(gf)9","title":"echxanh","icon":"9.gif","group":"echxanh","group_name":"\u1ebech xanh"},


{"syntax":"(on)1","title":"onion","icon":"1.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)10","title":"onion","icon":"10.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)100","title":"onion","icon":"100.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)101","title":"onion","icon":"101.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)102","title":"onion","icon":"102.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)103","title":"onion","icon":"103.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)104","title":"onion","icon":"104.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)105","title":"onion","icon":"105.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)106","title":"onion","icon":"106.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)107","title":"onion","icon":"107.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)108","title":"onion","icon":"108.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)109","title":"onion","icon":"109.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)11","title":"onion","icon":"11.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)110","title":"onion","icon":"110.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)111","title":"onion","icon":"111.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)112","title":"onion","icon":"112.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)113","title":"onion","icon":"113.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)114","title":"onion","icon":"114.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)115","title":"onion","icon":"115.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)116","title":"onion","icon":"116.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)117","title":"onion","icon":"117.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)118","title":"onion","icon":"118.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)119","title":"onion","icon":"119.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)12","title":"onion","icon":"12.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)120","title":"onion","icon":"120.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)121","title":"onion","icon":"121.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)122","title":"onion","icon":"122.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)123","title":"onion","icon":"123.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)124","title":"onion","icon":"124.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)125","title":"onion","icon":"125.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)126","title":"onion","icon":"126.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)127","title":"onion","icon":"127.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)128","title":"onion","icon":"128.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)129","title":"onion","icon":"129.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)13","title":"onion","icon":"13.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)130","title":"onion","icon":"130.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)131","title":"onion","icon":"131.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)132","title":"onion","icon":"132.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)133","title":"onion","icon":"133.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)134","title":"onion","icon":"134.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)135","title":"onion","icon":"135.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)136","title":"onion","icon":"136.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)137","title":"onion","icon":"137.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)138","title":"onion","icon":"138.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)139","title":"onion","icon":"139.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)14","title":"onion","icon":"14.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)15","title":"onion","icon":"15.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)16","title":"onion","icon":"16.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)17","title":"onion","icon":"17.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)18","title":"onion","icon":"18.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)19","title":"onion","icon":"19.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)2","title":"onion","icon":"2.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)20","title":"onion","icon":"20.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)21","title":"onion","icon":"21.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)22","title":"onion","icon":"22.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)23","title":"onion","icon":"23.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)24","title":"onion","icon":"24.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)25","title":"onion","icon":"25.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)26","title":"onion","icon":"26.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)27","title":"onion","icon":"27.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)28","title":"onion","icon":"28.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)29","title":"onion","icon":"29.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)3","title":"onion","icon":"3.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)30","title":"onion","icon":"30.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)31","title":"onion","icon":"31.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)32","title":"onion","icon":"32.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)33","title":"onion","icon":"33.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)34","title":"onion","icon":"34.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)35","title":"onion","icon":"35.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)36","title":"onion","icon":"36.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)37","title":"onion","icon":"37.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)38","title":"onion","icon":"38.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)39","title":"onion","icon":"39.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)4","title":"onion","icon":"4.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)40","title":"onion","icon":"40.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)41","title":"onion","icon":"41.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)42","title":"onion","icon":"42.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)43","title":"onion","icon":"43.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)44","title":"onion","icon":"44.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)45","title":"onion","icon":"45.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)46","title":"onion","icon":"46.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)47","title":"onion","icon":"47.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)48","title":"onion","icon":"48.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)49","title":"onion","icon":"49.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)5","title":"onion","icon":"5.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)50","title":"onion","icon":"50.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)51","title":"onion","icon":"51.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)52","title":"onion","icon":"52.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)53","title":"onion","icon":"53.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)54","title":"onion","icon":"54.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)55","title":"onion","icon":"55.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)56","title":"onion","icon":"56.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)57","title":"onion","icon":"57.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)58","title":"onion","icon":"58.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)59","title":"onion","icon":"59.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)6","title":"onion","icon":"6.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)60","title":"onion","icon":"60.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)61","title":"onion","icon":"61.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)62","title":"onion","icon":"62.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)63","title":"onion","icon":"63.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)64","title":"onion","icon":"64.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)65","title":"onion","icon":"65.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)66","title":"onion","icon":"66.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)67","title":"onion","icon":"67.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)68","title":"onion","icon":"68.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)69","title":"onion","icon":"69.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)7","title":"onion","icon":"7.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)70","title":"onion","icon":"70.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)71","title":"onion","icon":"71.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)72","title":"onion","icon":"72.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)73","title":"onion","icon":"73.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)74","title":"onion","icon":"74.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)75","title":"onion","icon":"75.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)76","title":"onion","icon":"76.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)77","title":"onion","icon":"77.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)78","title":"onion","icon":"78.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)79","title":"onion","icon":"79.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)8","title":"onion","icon":"8.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)80","title":"onion","icon":"80.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)81","title":"onion","icon":"81.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)82","title":"onion","icon":"82.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)83","title":"onion","icon":"83.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)84","title":"onion","icon":"84.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)85","title":"onion","icon":"85.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)86","title":"onion","icon":"86.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)87","title":"onion","icon":"87.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)88","title":"onion","icon":"88.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)89","title":"onion","icon":"89.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)9","title":"onion","icon":"9.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)90","title":"onion","icon":"90.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)91","title":"onion","icon":"91.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)92","title":"onion","icon":"92.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)93","title":"onion","icon":"93.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)94","title":"onion","icon":"94.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)95","title":"onion","icon":"95.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)96","title":"onion","icon":"96.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)97","title":"onion","icon":"97.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)98","title":"onion","icon":"98.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},
{"syntax":"(on)99","title":"onion","icon":"99.gif","group":"onion","group_name":"C\u1ee7 h\u00e0nh"},


{"syntax":"(po)1","title":"popo","icon":"1.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)10","title":"popo","icon":"10.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)11","title":"popo","icon":"11.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)12","title":"popo","icon":"12.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)13","title":"popo","icon":"13.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)14","title":"popo","icon":"14.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)15","title":"popo","icon":"15.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)16","title":"popo","icon":"16.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)17","title":"popo","icon":"17.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)18","title":"popo","icon":"18.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)19","title":"popo","icon":"19.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)2","title":"popo","icon":"2.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)20","title":"popo","icon":"20.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)21","title":"popo","icon":"21.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)22","title":"popo","icon":"22.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)23","title":"popo","icon":"23.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)24","title":"popo","icon":"24.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)25","title":"popo","icon":"25.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)26","title":"popo","icon":"26.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)27","title":"popo","icon":"27.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)28","title":"popo","icon":"28.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)29","title":"popo","icon":"29.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)3","title":"popo","icon":"3.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)30","title":"popo","icon":"30.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)31","title":"popo","icon":"31.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)32","title":"popo","icon":"32.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)33","title":"popo","icon":"33.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)34","title":"popo","icon":"34.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)35","title":"popo","icon":"35.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)36","title":"popo","icon":"36.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)37","title":"popo","icon":"37.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)38","title":"popo","icon":"38.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)39","title":"popo","icon":"39.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)4","title":"popo","icon":"4.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)40","title":"popo","icon":"40.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)41","title":"popo","icon":"41.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)42","title":"popo","icon":"42.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)43","title":"popo","icon":"43.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)44","title":"popo","icon":"44.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)45","title":"popo","icon":"45.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)46","title":"popo","icon":"46.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)5","title":"popo","icon":"5.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)6","title":"popo","icon":"6.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)7","title":"popo","icon":"7.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)8","title":"popo","icon":"8.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},
{"syntax":"(po)9","title":"popo","icon":"9.gif","group":"popo","group_name":"H\u00e0i h\u01b0\u1edbc"},


{"syntax":"(rf)1","title":"redfox","icon":"1.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)10","title":"redfox","icon":"10.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)11","title":"redfox","icon":"11.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)12","title":"redfox","icon":"12.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)13","title":"redfox","icon":"13.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)14","title":"redfox","icon":"14.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)15","title":"redfox","icon":"15.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)16","title":"redfox","icon":"16.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)17","title":"redfox","icon":"17.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)18","title":"redfox","icon":"18.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)19","title":"redfox","icon":"19.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)2","title":"redfox","icon":"2.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)20","title":"redfox","icon":"20.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)21","title":"redfox","icon":"21.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)22","title":"redfox","icon":"22.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)23","title":"redfox","icon":"23.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)24","title":"redfox","icon":"24.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)25","title":"redfox","icon":"25.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)26","title":"redfox","icon":"26.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)27","title":"redfox","icon":"27.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)28","title":"redfox","icon":"28.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)29","title":"redfox","icon":"29.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)3","title":"redfox","icon":"3.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)30","title":"redfox","icon":"30.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)31","title":"redfox","icon":"31.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)32","title":"redfox","icon":"32.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)33","title":"redfox","icon":"33.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)34","title":"redfox","icon":"34.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)35","title":"redfox","icon":"35.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)36","title":"redfox","icon":"36.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)37","title":"redfox","icon":"37.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)38","title":"redfox","icon":"38.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)39","title":"redfox","icon":"39.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)4","title":"redfox","icon":"4.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)5","title":"redfox","icon":"5.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)6","title":"redfox","icon":"6.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)7","title":"redfox","icon":"7.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)8","title":"redfox","icon":"8.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},
{"syntax":"(rf)9","title":"redfox","icon":"9.gif","group":"redfox","group_name":"C\u00e1o \u0111\u1ecf"},


{"syntax":"(rs)1","title":"redshit","icon":"1.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)10","title":"redshit","icon":"10.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)11","title":"redshit","icon":"11.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)12","title":"redshit","icon":"12.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)13","title":"redshit","icon":"13.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)14","title":"redshit","icon":"14.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)15","title":"redshit","icon":"15.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)2","title":"redshit","icon":"2.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)3","title":"redshit","icon":"3.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)4","title":"redshit","icon":"4.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)5","title":"redshit","icon":"5.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)6","title":"redshit","icon":"6.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)7","title":"redshit","icon":"7.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)8","title":"redshit","icon":"8.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},
{"syntax":"(rs)9","title":"redshit","icon":"9.gif","group":"redshit","group_name":"Shit \u0111\u1ecf"},


{"syntax":"(sc)1","title":"shin","icon":"1.jpeg","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)10","title":"shin","icon":"10.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)11","title":"shin","icon":"11.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)12","title":"shin","icon":"12.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)13","title":"shin","icon":"13.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)14","title":"shin","icon":"14.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)15","title":"shin","icon":"15.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)16","title":"shin","icon":"16.jpeg","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)17","title":"shin","icon":"17.jpeg","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)18","title":"shin","icon":"18.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)19","title":"shin","icon":"19.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)2","title":"shin","icon":"2.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)20","title":"shin","icon":"20.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)21","title":"shin","icon":"21.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)22","title":"shin","icon":"22.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)23","title":"shin","icon":"23.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)24","title":"shin","icon":"24.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)26","title":"shin","icon":"26.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)27","title":"shin","icon":"27.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)28","title":"shin","icon":"28.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)29","title":"shin","icon":"29.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)3","title":"shin","icon":"3.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)30","title":"shin","icon":"30.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)31","title":"shin","icon":"31.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)32","title":"shin","icon":"32.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)33","title":"shin","icon":"33.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)34","title":"shin","icon":"34.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)35","title":"shin","icon":"35.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)36","title":"shin","icon":"36.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)37","title":"shin","icon":"37.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)38","title":"shin","icon":"38.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)39","title":"shin","icon":"39.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)4","title":"shin","icon":"4.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)41","title":"shin","icon":"41.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)44","title":"shin","icon":"44.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)45","title":"shin","icon":"45.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)46","title":"shin","icon":"46.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)5","title":"shin","icon":"5.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)50","title":"shin","icon":"50.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)52","title":"shin","icon":"52.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)55","title":"shin","icon":"55.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)56","title":"shin","icon":"56.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)6","title":"shin","icon":"6.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)61","title":"shin","icon":"61.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)62","title":"shin","icon":"62.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)64","title":"shin","icon":"64.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)66","title":"shin","icon":"66.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)67","title":"shin","icon":"67.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)69","title":"shin","icon":"69.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)7","title":"shin","icon":"7.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)74","title":"shin","icon":"74.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)76","title":"shin","icon":"76.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)77","title":"shin","icon":"77.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)8","title":"shin","icon":"8.gif","group":"shin","group_name":"Shin chan"},
{"syntax":"(sc)9","title":"shin","icon":"9.gif","group":"shin","group_name":"Shin chan"},


{"syntax":"(sd)1","title":"soldier","icon":"1.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)10","title":"soldier","icon":"10.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)100","title":"soldier","icon":"100.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)101","title":"soldier","icon":"101.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)102","title":"soldier","icon":"102.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)103","title":"soldier","icon":"103.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)104","title":"soldier","icon":"104.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)105","title":"soldier","icon":"105.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)106","title":"soldier","icon":"106.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)107","title":"soldier","icon":"107.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)108","title":"soldier","icon":"108.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)109","title":"soldier","icon":"109.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)11","title":"soldier","icon":"11.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)110","title":"soldier","icon":"110.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)111","title":"soldier","icon":"111.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)112","title":"soldier","icon":"112.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)113","title":"soldier","icon":"113.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)114","title":"soldier","icon":"114.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)115","title":"soldier","icon":"115.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)116","title":"soldier","icon":"116.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)117","title":"soldier","icon":"117.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)118","title":"soldier","icon":"118.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)119","title":"soldier","icon":"119.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)12","title":"soldier","icon":"12.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)120","title":"soldier","icon":"120.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)121","title":"soldier","icon":"121.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)122","title":"soldier","icon":"122.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)13","title":"soldier","icon":"13.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)14","title":"soldier","icon":"14.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)15","title":"soldier","icon":"15.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)16","title":"soldier","icon":"16.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)17","title":"soldier","icon":"17.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)18","title":"soldier","icon":"18.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)19","title":"soldier","icon":"19.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)2","title":"soldier","icon":"2.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)20","title":"soldier","icon":"20.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)21","title":"soldier","icon":"21.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)22","title":"soldier","icon":"22.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)23","title":"soldier","icon":"23.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)24","title":"soldier","icon":"24.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)25","title":"soldier","icon":"25.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)26","title":"soldier","icon":"26.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)27","title":"soldier","icon":"27.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)28","title":"soldier","icon":"28.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)29","title":"soldier","icon":"29.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)3","title":"soldier","icon":"3.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)30","title":"soldier","icon":"30.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)31","title":"soldier","icon":"31.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)32","title":"soldier","icon":"32.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)33","title":"soldier","icon":"33.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)34","title":"soldier","icon":"34.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)35","title":"soldier","icon":"35.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)36","title":"soldier","icon":"36.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)37","title":"soldier","icon":"37.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)38","title":"soldier","icon":"38.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)39","title":"soldier","icon":"39.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)4","title":"soldier","icon":"4.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)40","title":"soldier","icon":"40.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)41","title":"soldier","icon":"41.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)42","title":"soldier","icon":"42.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)43","title":"soldier","icon":"43.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)44","title":"soldier","icon":"44.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)45","title":"soldier","icon":"45.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)46","title":"soldier","icon":"46.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)47","title":"soldier","icon":"47.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)48","title":"soldier","icon":"48.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)49","title":"soldier","icon":"49.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)5","title":"soldier","icon":"5.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)50","title":"soldier","icon":"50.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)51","title":"soldier","icon":"51.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)52","title":"soldier","icon":"52.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)53","title":"soldier","icon":"53.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)54","title":"soldier","icon":"54.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)55","title":"soldier","icon":"55.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)56","title":"soldier","icon":"56.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)57","title":"soldier","icon":"57.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)58","title":"soldier","icon":"58.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)59","title":"soldier","icon":"59.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)6","title":"soldier","icon":"6.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)60","title":"soldier","icon":"60.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)61","title":"soldier","icon":"61.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)62","title":"soldier","icon":"62.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)63","title":"soldier","icon":"63.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)64","title":"soldier","icon":"64.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)65","title":"soldier","icon":"65.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)66","title":"soldier","icon":"66.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)67","title":"soldier","icon":"67.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)68","title":"soldier","icon":"68.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)69","title":"soldier","icon":"69.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)7","title":"soldier","icon":"7.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)70","title":"soldier","icon":"70.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)71","title":"soldier","icon":"71.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)72","title":"soldier","icon":"72.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)73","title":"soldier","icon":"73.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)74","title":"soldier","icon":"74.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)75","title":"soldier","icon":"75.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)76","title":"soldier","icon":"76.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)77","title":"soldier","icon":"77.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)78","title":"soldier","icon":"78.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)79","title":"soldier","icon":"79.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)8","title":"soldier","icon":"8.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)80","title":"soldier","icon":"80.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)81","title":"soldier","icon":"81.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)82","title":"soldier","icon":"82.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)83","title":"soldier","icon":"83.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)84","title":"soldier","icon":"84.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)85","title":"soldier","icon":"85.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)86","title":"soldier","icon":"86.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)87","title":"soldier","icon":"87.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)88","title":"soldier","icon":"88.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)89","title":"soldier","icon":"89.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)9","title":"soldier","icon":"9.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)90","title":"soldier","icon":"90.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)91","title":"soldier","icon":"91.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)92","title":"soldier","icon":"92.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)93","title":"soldier","icon":"93.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)94","title":"soldier","icon":"94.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)95","title":"soldier","icon":"95.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)96","title":"soldier","icon":"96.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)97","title":"soldier","icon":"97.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)98","title":"soldier","icon":"98.gif","group":"soldier","group_name":"Soldier"},
{"syntax":"(sd)99","title":"soldier","icon":"99.gif","group":"soldier","group_name":"Soldier"},


{"syntax":"(tz)1","title":"tuzki","icon":"1.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)10","title":"tuzki","icon":"10.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)11","title":"tuzki","icon":"11.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)12","title":"tuzki","icon":"12.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)13","title":"tuzki","icon":"13.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)14","title":"tuzki","icon":"14.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)15","title":"tuzki","icon":"15.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)16","title":"tuzki","icon":"16.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)17","title":"tuzki","icon":"17.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)18","title":"tuzki","icon":"18.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)19","title":"tuzki","icon":"19.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)2","title":"tuzki","icon":"2.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)20","title":"tuzki","icon":"20.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)21","title":"tuzki","icon":"21.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)22","title":"tuzki","icon":"22.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)23","title":"tuzki","icon":"23.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)24","title":"tuzki","icon":"24.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)25","title":"tuzki","icon":"25.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)26","title":"tuzki","icon":"26.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)27","title":"tuzki","icon":"27.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)28","title":"tuzki","icon":"28.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)29","title":"tuzki","icon":"29.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)3","title":"tuzki","icon":"3.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)30","title":"tuzki","icon":"30.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)31","title":"tuzki","icon":"31.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)32","title":"tuzki","icon":"32.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)33","title":"tuzki","icon":"33.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)34","title":"tuzki","icon":"34.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)35","title":"tuzki","icon":"35.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)36","title":"tuzki","icon":"36.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)37","title":"tuzki","icon":"37.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)38","title":"tuzki","icon":"38.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)39","title":"tuzki","icon":"39.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)4","title":"tuzki","icon":"4.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)40","title":"tuzki","icon":"40.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)41","title":"tuzki","icon":"41.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)42","title":"tuzki","icon":"42.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)43","title":"tuzki","icon":"43.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)44","title":"tuzki","icon":"44.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)45","title":"tuzki","icon":"45.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)46","title":"tuzki","icon":"46.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)47","title":"tuzki","icon":"47.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)48","title":"tuzki","icon":"48.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)49","title":"tuzki","icon":"49.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)5","title":"tuzki","icon":"5.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)50","title":"tuzki","icon":"50.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)51","title":"tuzki","icon":"51.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)52","title":"tuzki","icon":"52.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)53","title":"tuzki","icon":"53.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)54","title":"tuzki","icon":"54.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)55","title":"tuzki","icon":"55.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)56","title":"tuzki","icon":"56.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)57","title":"tuzki","icon":"57.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)58","title":"tuzki","icon":"58.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)59","title":"tuzki","icon":"59.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)6","title":"tuzki","icon":"6.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)60","title":"tuzki","icon":"60.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)61","title":"tuzki","icon":"61.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)62","title":"tuzki","icon":"62.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)63","title":"tuzki","icon":"63.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)64","title":"tuzki","icon":"64.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)65","title":"tuzki","icon":"65.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)66","title":"tuzki","icon":"66.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)67","title":"tuzki","icon":"67.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)68","title":"tuzki","icon":"68.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)69","title":"tuzki","icon":"69.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)7","title":"tuzki","icon":"7.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)70","title":"tuzki","icon":"70.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)71","title":"tuzki","icon":"71.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)72","title":"tuzki","icon":"72.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)73","title":"tuzki","icon":"73.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)74","title":"tuzki","icon":"74.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)75","title":"tuzki","icon":"75.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)76","title":"tuzki","icon":"76.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)77","title":"tuzki","icon":"77.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)78","title":"tuzki","icon":"78.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)79","title":"tuzki","icon":"79.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)8","title":"tuzki","icon":"8.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)80","title":"tuzki","icon":"80.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)81","title":"tuzki","icon":"81.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)82","title":"tuzki","icon":"82.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)83","title":"tuzki","icon":"83.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)84","title":"tuzki","icon":"84.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)85","title":"tuzki","icon":"85.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)86","title":"tuzki","icon":"86.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)87","title":"tuzki","icon":"87.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)88","title":"tuzki","icon":"88.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)89","title":"tuzki","icon":"89.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)9","title":"tuzki","icon":"9.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)90","title":"tuzki","icon":"90.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)91","title":"tuzki","icon":"91.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)92","title":"tuzki","icon":"92.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)93","title":"tuzki","icon":"93.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"},
{"syntax":"(tz)94","title":"tuzki","icon":"94.gif","group":"tuzki","group_name":"L\u1ea3 l\u01b0\u1edbt"}
]
		};
		if(settings) $.extend(_cfg, settings);
		var obj = this;
		var default_label = $(_cfg.handle).html();
		var default_style = $(_cfg.handle).attr('style');
		var default_css = $(_cfg.handle).attr('class');
		var funct = {
			__regexp: function(str){
				return str.replace(/(\.|\\|\+|\*|\?|\[|\^|\]|\$|\(|\)|\{|\}|\=|\!|\<|\>|\||\:|\-)/ig,"\\$1");
			},
			__load: function(){ // apply emotion
				if(more_emotions){
					$.each(more_emotions,function(id,val){
						if(_cfg.r_alert && _cfg.emotions[id]){
							if(confirm('Emotion '+id+'.'+_cfg.emotion_ext+' <=> '+_cfg.emotions[id]+' does exists. Do you want to replace it by '+val+' ?')) _cfg.emotions[id] = val;
						}else{
							_cfg.emotions[id] = val;
						}
					});
				}
				obj.each(function(){
					var str = $(this).html();
					$.each(_cfg.emotions,function(iEM,bbcode){
						if(bbcode.group)
							str = str.replace(new RegExp(funct.__regexp(bbcode.syntax),'ig'),'<span class="emotion_show '+iEM+'"><img  src="'+_cfg.dir+ bbcode.group + '/' + bbcode.icon+'" title="'+bbcode.title+'" /></span>');
						else
							str = str.replace(new RegExp(funct.__regexp(bbcode.syntax),'ig'),'<span class="emotion_show '+iEM+'"><img  src="'+_cfg.dir+bbcode.icon+'" title="'+bbcode.title+'" /></span>');
					});
					$(this).html(str);
					$(_cfg.handle).html(default_label).attr({'style':default_style}).addClass(default_css);
				})
			},
			__remove: function(){ // remove emotion
				$(obj).find('span.emotion_show').each(function(){
					var iE = Number(this.className.split('emotion_show ')[1]);
					$(this).attr({'class':''}).addClass('emotion_hide '+iE).html(_cfg.emotions[iE].syntax);		
				});
				$(_cfg.handle).html(_cfg.label).attr({'style':_cfg.style}).addClass(_cfg.cls);
			},
			__again: function(){
				$(obj).find('span.emotion_hide').each(function(){
					var iE = Number(this.className.split('emotion_hide ')[1]);
					$(this).attr({'class':''}).addClass('emotion_show '+iE).html('<img  src="'+_cfg.dir+_cfg.emotions[iE].icon+'" title="'+_cfg.emotions[iE].title+'" />');
				});
				$(_cfg.handle).html(default_label).attr({'style':default_style}).addClass(default_css);
			}
		};
		
		$(_cfg.handle).toggle(funct.__remove,funct.__again);
		funct.__load();
		return false;
	};
})(jQuery)