<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>XWEB XAdmin</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<?php //$this->html->loadCss("Content/XAdmin/css/global.css")?>
<!--[if IE]>
<?php //$this->html->loadCss("Content/XAdmin/css/iefix.css")?>
<![endif]-->
<!--[if IE 7]>
<?php //$this->html->loadCss("Content/XAdmin/css/ie7fix.css")?>
<![endif]-->
<style type="text/css">
#access-body{
	height: 100px;
	text-align: center;
}
.deniedTitle{
	color: #C36; 
	text-transform: uppercase; 
	padding-top: 20px; 
	font-size: 20pt;
}
.deniedBack{
	color: #0095C3 !important;
	font-size: 11pt;
	text-decoration: none;
}
.deniedBack:hover{
	text-decoration: underline;
}
</style>
</head>
<body>
<div id="access-shell">
<!-- ********************************************************************* -->
	<!-- Begin Black Header with logo -->
	<div id="access-header">
		<img src="<?php //echo $this->url->content("Content/XAdmin/img/logo.png")?>" style="padding-top: 10px;" />
	</div>
	<!-- End Black Header with logo -->
<!-- ********************************************************************* -->


<!-- ********************************************************************* -->
	<!-- Begin Main Content for Access Page (See Section M in custom.js) -->
	<div id="access-body">
		<h1 class="deniedTitle">Access Denied !</h1>
		<br />
		<a href="javascript:void(0)" class="deniedBack" onclick="history.back()">Quay trở về trang trước</a>
	</div>

	<!-- //End Main Content for Access Page -->
<!-- ********************************************************************* -->
</div>

<!-- ********************************************************************* -->
<!-- Begin Javascript Files -->
<?php /*$this->html->loadJs(
        array(		"Scripts/jquery-1.6.2.min.js",
                    "Scripts/jquery-ui-1.8.16.min.js",
                    "Content/XAdmin/js/jquery.visualize.js",
                    "Content/XAdmin/js/jquery.visualize.tooltip.js",
                    "Content/XAdmin/js/jquery.ui.selectmenu.js",
                    "Content/XAdmin/js/jquery.datatables.min.js",
                    "Content/XAdmin/js/jquery.potato.menu.min.js",
                    "Content/XAdmin/js/jquery.masonry.min.js",
                    "Content/XAdmin/js/jquery.lightbox.min.js",
                    "Content/XAdmin/js/jquery.ui.totop.js",
                    "Content/XAdmin/js/jquery.markitup.js",
                    "Content/XAdmin/js/jquery.markitup.set.js",
                    "Content/XAdmin/js/jquery.filetree.js",
                    "Content/XAdmin/js/jquery.minicolors.js",
                    "Content/XAdmin/js/custom.js"	
                )
)*/?>
<!--[if IE]>
<?php //$this->html->loadJs("Content/XAdmin/js/excanvas.compiled.js")?>
<![endif]--><!-- needed to make HTML5 charts and graphs (visualize.js) work in IE -->

<!--show password script for registration section in login page-->
<?php //$this->html->loadJs("Content/XAdmin/js/jquery.showpassword.js")?>

<!-- //End Javascript Files -->
<!-- ********************************************************************* -->
</body>
</html>