<?php $this->content->begin() ?>
<div class="fll left-content">
    <div class="box-daotao">
        <ul class="lstTab spr pRel">
            <li class="fll"><span>LIÊN HỆ</span></li>
        </ul>
        <div class="box-lienhe">
            <h1>TRƯỜNG CAO ĐẲNG Y HÀ NAM</h1>
            <img src="/Content/default/images/lienhe.jpg">
            <p>Địa chỉ: Nguyễn Hữu Tiến - Lê Hồng Phong - TP. Phủ Lý - T. Hà Nam</p>
            <p>Điện thoại: 03513.851.189</p>
            <p>Fax: 03513.851.189</p>
            <p style="color:  <?php if($alert['success']) echo "green"; else echo "red"; ?>; font-weight: bold;">
                <?php if(isset($alert)): ?>
                    <?php echo $alert['message']; ?>
                <?php endif; ?>
            </p>
            <?php $this->form->begin('contactForm', array('action' => $this->url->action('index'), "class"=>"form")); ?>
                <label>Người gửi<i>*</i></label><?php $this->form->textboxFor('name', array('id' => 'ctrl_name')) ?><br>
                <label>Email gửi<i>*</i></label><?php $this->form->textboxFor('email', array('id' => 'ctrl_email')) ?><br>
                <label>Địa chỉ</label><?php $this->form->textboxFor('address', array('id' => 'ctrl_address')) ?><br>
                <label>Điện thoại</label><?php $this->form->textboxFor('phone', array('id' => 'ctrl_phone')) ?><br>
                <label>Tiêu đề <i>*</i></label><?php $this->form->textboxFor('title', array('id' => 'ctrl_title')) ?><br>
                <label class="pRel labnd">Nội dung <i>*</i></label><?php $this->form->textareaFor('message') ?><br>
                <span>Tối đa <b>1000</b> ký tự</span><br />
                <label>Mã kiểm tra: <i>*</i></label> <input type="text" name="captcha" value="" id="ctrl_code" class="textCtrl short"><br />
                <img src="<?php echo $this->url->action('captcha', 'Assets', '') ?>" alt="captcha" > <br />
                    
                <input type="submit" name="save" value="Gửi" class="submittext" >
            <?php $this->form->end(); ?>
        </div>
    </div>
</div>
<?php
$this->content->end()?>