<!-- ********************************************************************* -->
<!-- Begin Footer -->
<!--<div id="global-footer">
	<ul>
		<li>&copy; XADMIN</li>
		<li class="no-border"><a href="http://xweb.vn">Xweb Việt Nam</a></li>
		<li class="right"><a href="./8.html">Hỗ trợ</a></li>
		<li class="right no-border"><a href="<?php //echo $this->url->action("index", "Admin", "Dashboard")?>">Trang chủ</a></li>
	</ul>
</div>
--><!-- //End Footer -->
<!-- ********************************************************************* -->

<!-- XSystemAdmin - Footer -->

<!-- ********************************************************************* -->