<label for="value">Trang nội dung</label>
<div>
    <select id="value" name="value">
        <?php foreach($pages as $p):
            $url = $this->url->action('index', 'Index', 'Page', array('seo_url' => $p->seo_url,
                                                                      'id'      => $p->id));
        ?>
        <option data-url="<?php echo $url?>" value="<?php echo $p->id?>" <?php if($value == $p->id){?>selected="selected"<?php }?>><?php echo $p->title?></option>
        <?php endforeach?>
    </select>
    <label class="red" for="value">*</label>
</div>