<?php $this->content->begin() ?>
<div class="content indexContent">
    <div class="firstContent">
        <div class="blockTop">
            <div class="block first">
                <div class="blockIcon"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/about-icon.png") ?>"/></div>
                <div class="blockTitle"><a href="<?php echo $this->url->action('index','Index','Page') ?>">Giới thiệu</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="block last">
                <div class="blockIcon"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/service-icon.png") ?>"/></div>
                <div class="blockTitle"><a href="<?php echo $this->url->action('index','Index','Video') ?>">Dịch vụ</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="blockBottom">
            <div class="block first">
                <div class="blockIcon"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/project-icon.png") ?>"/></div>
                <div class="blockTitle"><a href="<?php echo $this->url->action('index','Index','Project') ?>">Dự Án</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="block last">
                <div class="blockIcon"><img src="<?php echo $this->url->content("Content/VNCPC/images/icons/product-icon.png") ?>"/></div>
                <div class="blockTitle"><a href="<?php echo $this->url->action("index", "Index", "Document")?>">Ấn phẩm</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="secondContent">
        <?php $count = 1;?>
        <?php foreach($projects as $project): ?>
            <div class="block <?php echo getClass($count);?>">
                <div class="blockIcon"><span><?php echo $count;?></span></div>
                <div class="blockTitle">
                    <a href="<?php echo $this->url->action("detail", "Index", "Artical", array('id'=>$project[0]->id, 'title'=>$project[0]->seo_url)) ?>" class="first"><?php echo $project[0]->title?></a>
                    <a href="<?php echo $this->url->action("detail", "Index", "Artical", array('id'=>$project[1]->id, 'title'=>$project[1]->seo_url)) ?>" class="second"><?php echo $project[1]->title?></a>
                </div>
                <div class="clearfix"></div>
                <?php $count++;?>
            </div>
        <?php endforeach;?>
    </div>
    <div class="clearfix"></div>
</div>

<?php
function getClass($count) {
    if($count==1) return 'first top';
    elseif($count ==2) return 'top';
    elseif($count ==3) return 'left';
    else return 'last';
}

function replaceSpace($str) {
    return str_replace(' ', '-', stripUnicode($str));
}

function stripUnicode($str){
    $str = preg_replace("/(à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ)/", 'a', $str);
    $str = preg_replace("/(è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ)/", 'e', $str);
    $str = preg_replace("/(ì|í|ị|ỉ|ĩ)/", 'i', $str);
    $str = preg_replace("/(ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ)/", 'o', $str);
    $str = preg_replace("/(ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ)/", 'u', $str);
    $str = preg_replace("/(ỳ|ý|ỵ|ỷ|ỹ)/", 'y', $str);
    $str = preg_replace("/(đ)/", 'd', $str);
    $str = preg_replace("/(À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ)/", 'A', $str);
    $str = preg_replace("/(È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ)/", 'E', $str);
    $str = preg_replace("/(Ì|Í|Ị|Ỉ|Ĩ)/", 'I', $str);
    $str = preg_replace("/(Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ)/", 'O', $str);
    $str = preg_replace("/(Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ)/", 'U', $str);
    $str = preg_replace("/(Ỳ|Ý|Ỵ|Ỷ|Ỹ)/", 'Y', $str);
    $str = preg_replace("/(Đ)/", 'D', $str);
//$str = str_replace(" ", "-", str_replace("&amp;*#39;","",$str));
    return $str;
}
?>
<?php $this->content->end() ?>