<?php $this->content->begin() ?>
<div class="fll left-content">
    <div class="box-daotao">
        <ul class="lstTab spr pRel">
            <li class="fll"><span>HS - SV</span></li>
            <span class="pAbs navi-dt"><a href="#">Trang chủ</a>  Học sinh - sinh viên</span>
        </ul>
        <div class="content-hssv cf">
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Nội dung - Quy chế</a></h4>
            </div>
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Kết quả - học tập</a></h4>
            </div>
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Thời khóa biểu</a></h4>
            </div>
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Kế hoạch</a></h4>
            </div>
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Lịch thi</a></h4>
            </div>
            <div class="fll item-hssv pRel">
                <a href="#" class="pAbs img-sach"><img src="/Content/default/images/sach.jpg"></a>
                <h4><a href="#">Diễn đàn</a></h4>
            </div>
        </div>
    </div>
</div>
<?php $this->content->end() ?>