<?php $this->content->begin()?>
<div class="widget">
    <div class="header">
        <span><span class="ico  gray paragraph_justify"></span> Thêm menu cho <?php echo $heading?> </span>
    </div><!-- End header -->
    <div class="content">
        <div class="formEl_b">
            <?php
            $ajaxOption['begin'] = "begin";
            $ajaxOption['success'] = "success";
            $this->form->beginAjax($ajaxOption);
            ?>
            <?php $this->form->hiddenFor('url')?>
            <?php $this->form->hiddenFor("id")?>
            <?php $this->form->hiddenFor("type")?>
            <input type="hidden" id="currentValue" name="currentValue" value="<?php echo $this->model->value?>"/>
            <fieldset>
                <legend>Thông tin menu</legend>
                <div class="section">
                    <?php $this->form->labelFor("parent_id")?>
                    <div>
                        <?php $this->form->selectFor("parent_id", $menuOptions, null, null, array('data-placeholder' => "Lựa chọn danh mục cha...",
                                                                                                  'class' => "medium"))?>
                        <label class="red" for="parent_id">*</label>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("title")?>
                    <div>
                        <?php $this->form->textboxFor("title", array('class' => "medium"))?>
                        <label class="red">*</label>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("description")?>
                    <div>
                        <?php $this->form->textboxFor("description", array('class' => "large"))?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("sort")?>
                    <div>
                        <?php $this->form->textboxFor("sort")?>
                    </div>
                </div>
                <div class="section">
                    <?php $this->form->labelFor("node")?>
                    <div>
                        <select id="node" name="node" class="large">
                            <option value="0" data-url="<?php echo $this->url->action('urlNode')?>" <?php if($this->model->node == '0'){?>selected="selected"<?php }?>>Đường dẫn</option>
                            <?php foreach($nodesOptions as $n):
                            $url = $this->url->action($n->action, $n->controller, $n->module);
                            ?>
                            <?php if($n->is_category == '1'):?>
                            <optgroup label="<?php echo $n->title?>">
                                <?php foreach($n->subs as $ns):
                                $surl = $this->url->action($ns->action, $ns->controller, $ns->module);
                                ?>
                                <option value="<?php echo $ns->id?>" data-url="<?php echo $surl?>" <?php if($this->model->node == $ns->id){?>selected="selected"<?php }?>><?php echo $ns->title?></option>
                                <?php endforeach;?>
                            </optgroup>
                            <?php else:?>
                            <option value="<?php echo $n->id?>" data-url="<?php echo $url?>" <?php if($this->model->node == $n->id){?>selected="selected"<?php }?>><?php echo $n->title?></option>
                            <?php endif;?>
                            <?php endforeach;?>
                        </select>
                        <label class="red" for="node">*</label>
                    </div>
                </div>
                <div class="section" id="menu_node_container">
                </div>
                <div class="section last">
                    <div>
                        <input type="hidden" name="saveType" value="0" id="saveType" />
                        <input class="uibutton icon add" id="submit" type="submit" value="Sửa">
                        <input class="uibutton icon add" id="submit2" type="submit" value="Sửa và đóng" onclick="$('#saveType').val('1');">
                        <input class="uibutton special icon edit" type="reset" value="Nhập lại">
                        <a class="uibutton confirm icon answer" href="<?php echo $this->url->action("list", "Manager", "Navigation", array($navType))?>"><?php echo $heading?></a>
                    </div>
                </div>
            </fieldset>
            <?php $this->form->end()?>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js',
                          'Application/Modules/Navigation/Assets/js/create_manager.js'));
?>
<?php $this->section->end()?>