<div class="slider-wrapper theme-default">
    <div class="ribbon"></div>
    <div id="nslider" class="nivoSlider" style="width:720px; height:348px;">
        <?php foreach($slides as $slide):
        if(!empty($slide->link))
            $link = "onclick=\"window.location.href='" . $slide->link . "';\" style='cursor: pointer;'";
        else
            $link = "";
        ?>
        <img <?php echo $link?> src="<?php echo $slide->image?>" alt="<?php echo $slide->title?>" width="720" height="348" />
        <?php endforeach?>
    </div>
</div>