<?php $this->content->begin()?>
<?php $this->html->loadCss('Content/4love/css/login.css')?>
<?php $this->html->loadCss('Content/4love/css/custom.css')?>
<script language="javascript">
		$(function(){
			$('form').jqTransform({imgPath:'assets/jqtransformplugin/img/'});
		});
</script>
<div class="content connect-detail">
			<div class="box box-login box-shadown box-radius box-border box-bg-color-w">
            	<div class="left l1 box-radius">
            	    <div class="title">Quên mật khẩu</div>
                	<?php $this->form->begin()?>
                	<table cellpadding="0" cellspacing="0" border="0">
                    	<tr>
                        	<td valign="top"><?php $this->form->labelFor('email')?></td>
                            <td valign="top">
                            	<?php $this->form->textboxFor('email')?><div class="cl"></div>
                                <?php $this->form->validationMessage('email')?>
                                <div class="cl" style="height: 10px;"></div>
                            </td>
                        </tr>
                        <tr>
                        	<td></td>
                            <td style="padding: 5px 0;">
                            	<a href="<?php echo $this->url->action('login')?>">Quay lại trang đăng nhập ?</a>
                            </td>
                        </tr>
                        <tr id="loading">
									<td colspan="4" align="right">
										<div class="albox informationbox loading hidden" style="z-index: 680; width: 385px">
		                                	Xin vui lòng chờ trong giây lát...
		                                	<a href="javascript:void()" class="close tips" original-title="close"></a>
		                                </div>
									</td>
								</tr>
								<tr id="error">
									<td colspan="4" align="right">
										<div class="albox warningbox hidden" style="z-index: 680; width: 385px"">
		                                	<span></span>
		                                	<a href="javascript:void()" class="close tips" original-title="close"></a>
		                                </div>
									</td>
								</tr>
								<tr id="success">
									<td colspan="4" align="right">
										<div class="albox succesbox hidden" style="z-index: 680; width: 385px"">
		                                	<span></span>
		                                	<a href="javascript:void()" class="close tips" original-title="close"></a>
		                                </div>
									</td>
								</tr>
                        <tr>
                        	<td></td>
                            <td>
                            	<input type="image" src="<?php echo $this->url->content('Content/4love/images/laylaimatkhau.png')?>" />
                            </td>
                        </tr>
                    </table>
                    <?php $this->form->end()?>
                    <div class="intro-reg">
                    	<h4>Sẵn sàng để liên lạc ?</h4>
                        <a href="<?php echo $this->url->action('register', 'Member', 'Auth')?>" id="regnow"></a>
                        <p>* Chỉ có thành viên chính thức mới có đầy đủ các tính năng để liên lạc và tìm kiếm bạn trên 4love.vn >> <a href="<?php echo $this->url->action('register', 'Member', 'Auth')?>">Đăng kí ngay</a> để thành thành viên chính thức</p>
                    </div>
                </div>
                <div class="left l2 box-radius">
                	<div class="title">Cách để bạn tìm được người phù hợp trên 4love.vn</div>
                    <div class="cnt">
                    	<div class="b-img box-radius">
                        	<img src="<?php echo $this->url->content('Content/4love/images/huongdan.png') ?>" />
                        </div>
                    </div>
                </div>
                <div class="cl"></div>
            </div>
            <div class="hs"></div>
        	<?php $this->html->renderAction('footerw', 'Component', '')?>
    	</div>
<?php $this->html->loadJs('Application/Modules/Auth/Assets/js/member_forgot.js')?>
<?php $this->content->end()?>