<?php $this->content->begin() ?>
<div class="main-content">
    <!--<div class="intro-panel">
        <a href="" class="title"><?php echo $firstPage->title ?></a>
        <div class="cnt">
            <?php echo $firstPage->headline ?>
        </div>
    </div>-->
    <div class="speaker-panel">
        <a class="title"><?php echo $catName; ?></a>
        <div class="cnt">
            <ul>
                <?php $i=0; foreach($articals as $artical): ?>
                <li <?php if($i%2 == 1) echo 'class="last"'; $i++; ?>>
                    <div class="speaker">
                        <div class="avatar">
                            <img src="<?php echo $artical->image ?>" alt="" width="50" height="50" />
                        </div>
                        <div class="speaker-info">
                            <a href="<?php echo $this->url->action('index','Index','Artical', array('seo_url'=> $artical->seo_url,'id'=>$artical->id)) ?>" class="sp-title"><?php echo $artical->title ?></a>
                            <?php if($artical->category_id==1): ?>
                            <p class="sp">Diễn giả:</p>
                            <a class="sp-name"><?php echo $artical->description ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>        
                <?php endforeach; ?>
            </ul>
            <div class="cl"></div>
        </div>
        
    </div>
</div>
<div class="sidebar">
    <div class="news-panel">
        <a class="title"><?php echo $catName; ?></a>
        <div class="cnt">
            <ul>
                <?php foreach($news as $new): ?>
                <li>
                    <div class="news-item">
                        <a href="<?php echo $this->url->action('index','Index','Artical', array('seo_url'=> $new->seo_url,'id'=>$new->id)) ?>" class="n-title"><?php echo $new->title ?></a>
                        <p class="n-date"><?php echo date('d-m-Y', strtotime($new->created_date)) ?></p>
                    </div>
                </li>       
                <?php endforeach; ?>
            </ul>
            <a href="<?php echo $this->url->action('category','Index','Artical', array('seo_url'=> 'tin-tuc','id'=>2)) ?>" class="news-more">Các tin khác</a>
        </div>
    </div>
</div>
<div class="cl"></div>
<div class="main-intro">
    <?php $this->html->renderAction('index', 'BlockCom', 'Block', array('intro')) ?>
</div>
<?php $this->content->end() ?>