<?php $this->content->begin() ?>
<?php if ($category->seo_url == "dao-tao"): ?>
    <div class="fll left-content">
        <div class="box-daotao">
            <ul class="lstTab spr pRel">
                <li class="fll"><span>ĐÀO TẠO</span></li>
                <span class="pAbs navi-dt"><a href="<?php echo $this->url->action('index', 'Index', '') ?>">Trang chủ</a>  Đào tạo</span>
            </ul>
            <div class="box-daotaox">
                <div class="daotao-content">
                    <ul class="rs">
                        <?php foreach ($articals as $artical): ?>
                            <li>
                                <a href="<?php echo $this->url->action("new", "Index", "Artical", array('id' => $artical->id, 'title' => $artical->seo_url)) ?>"><?php echo XPHP_String::shortenText($artical->title, 120); ?></a>
                            </li>
                            <p style="font-size: 12px; color: #6a6a6a; margin-bottom: 10px;"><?php echo XPHP_String::shortenText($artical->description, 200); ?></p>
                        <?php endforeach; ?>
                    </ul>
                    <div class="paging">
                        <ul class="box-page rs cf">
                            <?php if ($page > 2): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page - 2) ?>" class="active"><?php echo $page - 2; ?></a></li><?php endif; ?>
                            <?php if ($page > 1): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page - 1) ?>" class="active"><?php echo $page - 1; ?></a></li><?php endif; ?>
                            <li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page) ?>"><?php echo $page ?></a></li>
                            <?php if (($page + 1) * $limit > $count && $page * $limit <= $count): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page + 1) ?>"><?php echo $page + 1 ?></a></li> <?php endif; ?>
                            <?php if (($page + 2) * $limit > $count && ($page + 1) * $limit <= $count): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page + 2) ?>"><?php echo $page + 2 ?></a></li><?php endif; ?>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
        <div class="box-tracuudiem">
            <div class="box-tracuu">
                <img src="/Content/default/images/img-lichti.jpg" class="pAbs">
                <h4 class="diemthi">TRA CỨU ĐIỂM THI</h4>
                <form>
                    <label>MÃ SV</label><input type="text" name="masv" value=""><br>
                    <label>Họ tên</label><input type="text" name="hoten" value=""><br>
                    <label>Môn</label><input type="text" name="mon" value="">
                </form>

            </div>
        </div>
    </div>
<?php else: ?>

    <div class="fll left-content">
        <div class="box-daotao">
            <ul class="lstTab spr pRel">
                <li class="fll"><span>TUYỂN SINH</span></li>
                <span class="pAbs navi-dt"><a href="#">Trang chủ</a>  Tuyển sinh</span>
            </ul>
            <div class="box-daotaox">
                <div class="tuyensinh-content">
                    <?php foreach ($articals as $artical): ?>
                    <div class="item-ts pRel">
                        <a href="<?php echo $this->url->action('detail','Index','Artical', array('title' => $artical->seo_url, 'id' => $artical->id)) ?>" class="pAbs img-tuyensinh">
                            <img src="/Thumb/phpThumb.php?src=<?php echo empty($artical->image) ? "/Content/default/images/tuyensinh.jpg" : $artical->image;?>&w=100&h=107&zc=1">
                        </a>
                        <h4 class="rs"><a href="<?php echo $this->url->action("new", "Index", "Artical", array('id'=>$artical->id, 'title'=>$artical->seo_url))?>"><?php echo XPHP_String::shortenText($artical->title); ?></a></h4>
                        <p><?php echo XPHP_String::shortenText($artical->description, 200) ?></p>
                    </div>
                    <?php endforeach; ?>
                    <ul class="box-page rs cf">
                        <?php if ($page > 2): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page - 2) ?>" class="active"><?php echo $page - 2; ?></a></li><?php endif; ?>
                        <?php if ($page > 1): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page - 1) ?>" class="active"><?php echo $page - 1; ?></a></li><?php endif; ?>
                        <li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page) ?>"><?php echo $page ?></a></li>
                        <?php if (($page + 1) * $limit <= $count || (($page + 1) * $limit > $count && $page * $limit <= $count)): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page + 1) ?>"><?php echo $page + 1 ?></a></li> <?php endif; ?>
                        <?php if (($page + 2) * $limit <= $count || (($page + 2) * $limit > $count && ($page + 1) * $limit <= $count)): ?><li class="fll"><a href="<?php echo $this->url->action('list', 'Index', 'Artical', array('title' => $category->seo_url, 'id' => $category->id)) . "?page=" . ($page + 2) ?>"><?php echo $page + 2 ?></a></li><?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php
$this->content->end()?>