<?php $this->content->begin()?>

<script type="text/javascript">

    $(document).ready(function(){
        $('#menuTintuc').addClass("active");
        $('.content').addClass("newsContent newsClickContent");
        $('.partnerLink').remove();


        function loadData(page){
            var url = "<?php echo $this->url->action('moreNews', 'Index', 'Artical'); ?>";
            $.ajax
            ({
                type: "POST",
                url: url,

                data: "page="+page+"&cat_id="+<?php echo (empty($category)) ? 0 : $category->id?>,
                success: function(msg)
                {
                    $(".newsList").ajaxComplete(function(event, request, settings)
                    {
                        $(".newsList").html(msg);
                    });
                }
            });
        }

        loadData(1);  // For first time page load default results
        $('.newsList .pageNav a').live('click',function(){
            var page = $(this).attr('p');
            loadData(page);

        });
    });

    //        function loadArtical(id) {
    //            $(".firstContent").load("/Artical/Index/load/"+id);
    //            return false;
    //        }

</script>
<?php
    function getClass($count) {
        if($count == 1 || $count == 4) return ' first';
        elseif($count == 2 || $count ==5) return '';
        else return ' last';
    }
?>
<div class="firstContent">
    <div class="blockNews groupThree left">
        <div class="blockTitle"><a href="#"><?php echo (empty($category)) ? 'Tin mới nhất' : $category->name?></a></div>
        <div class="newsGroup">
            <?php $count = 1;?>
            <?php foreach ($articals as $artical): ?>                
                <div class="newsItem<?php echo getClass($count);?>">
                    <img src="/Thumb/phpThumb.php?src=<?php echo (empty($artical->image)) ?  "/Content/VNCPC/images/contents/news1.png" : $artical->image;?>&w=320&h=300&zc=1" />
                    <div class="newsTitle"><a href="<?php echo $this->url->action("new", "Index", "Artical", array('id'=>$artical->id, 'title'=>$artical->seo_url))?>"><?php echo substr($artical->title, 0, 50); if(strlen($artical->title) > 50) echo " ..."; ?></a></div>
                    <div class="clearfix"></div>
                </div>
            <?php $count ++;?>
            <?php endforeach;?>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="secondContent">
    <div class="otherNews">
        <div class="otherNewsTitle">
            <a href="#">Tin Khác</a>
        </div>
        <div class="newsList"></div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="clearfix"></div>
<?php $this->content->end()?>