<?php $this->content->begin()?>

<?php
$per_page = 5;
$count = 10;
$pages = ceil($count/$per_page);
?>

<script type="text/javascript">

    $(document).ready(function(){



        //Default Starting Page Results

        $("#pagination li:first").css({'color' : '#FF0084'}).css({'border' : 'none'});

        $("#content").load("/Artical/Index/load/1");



        //Pagination Click
        $("#pagination li").click(function(){
            //CSS Styles
            $("#pagination li")
                .css({'border' : 'solid #dddddd 1px'})
                .css({'color' : '#0063DC'});

            $(this)
                .css({'color' : '#FF0084'})
                .css({'border' : 'none'});

            //Loading Data
            var pageNum = this.id;

            $("#content").load("/Artical/Index/load/" + pageNum);
        });


    });
</script>

<div align="center">



    <div id="content" ></div>
    <table width="800px">
        <tr>
            <Td>
                <ul id="pagination">
                    <?php
                    //Show page links
                    for($i=1; $i<=$pages; $i++)
                    {
                        echo '<li id="'.$i.'">'.$i.'</li>';
                    }
                    ?>
                </ul>
            </Td>
        </tr>
    </table>
</div>

<?php $this->content->end()?>
