<table>
    <tr>
        <td>Ethnic</td><td><?php if(isset($data->ethnic)) echo $ethnic[$data->ethnic] ?></td>
    </tr>
    <tr>
        <td>Ethnic About</td><td><?php echo $data->ethnicabout ?></td>
    </tr>
    <tr>
        <td>Religious</td><td><?php if(isset($data->religious)) echo $religious[$data->religious] ?></td>
    </tr>
    <tr>
        <td>Religious About</td><td><?php echo $data->religiousabout ?></td>
    </tr>
    <tr>
        <td>Edu</td><td><?php if(isset($data->edu)) echo $education[$data->edu] ?></td>
    </tr>
    <tr>
        <td>Edu About</td><td><?php echo $data->eduabout ?></td>
    </tr>
    <tr>
        <td>Speak</td><td><?php echo $data->speak ?></td>
    </tr>
    <tr>
        <td>Outlook</td><td><?php echo $data->outlook ?></td>
    </tr>
</table>