<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico gray administrator"></span>Thêm người dùng mới</span>
    </div>
    <div class="content">
        <div class="boxtitle min">Sửa thông tin người dùng</div>
        <?php
            $ajaxOption['begin'] = "begin";
            $ajaxOption['success'] = "success";
            $this->form->beginAjax($ajaxOption);
        ?>
            <?php //$this->form->hiddenFor("id")?>                
            <!-- Third / Half column-->
            <div class="widgets">
                <div class="oneThree">
                    <div class="profileSetting">
                        <div class="avartar"><img src="<?php echo $this->model->avatar?>" width="175" height="180" alt="Ảnh đại diện" /></div>
                        <div class="avartar">
                            <?php $this->form->textboxFor("avatar", array('class' => "large"))?>
                            <a id="open_icon" class="file-manager" data-type="image" title="Quản lý ảnh"  rel="avatar" >open</a> 
                            <p align="center"><span> OR </span>Take a picture with <a class="takeWebcam">Webcam</a></p>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="twoOne">
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("fullname")?>
                            <small>Vui lòng nhập họ</small>
                        </label>
                        <div> 
                            <?php $this->form->textboxFor("fullname", array('class' => 'validate[required] large'))?>
                            <?php $this->form->validationMessage("fullname")?>
                        </div>
                    </div>
                    
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("role_id", array('class' => 'normal-label'))?>
                            <small>Vui lòng chọn quyền</small>
                        </label>
                        <div> 
                            <?php $this->form->selectFor("role_id", $roleOptions)?>
				            <?php $this->form->validationMessage("role_id")?>
                        </div>
                    </div>
                    <div class="section">
                        <label>
                            <?php $this->form->labelFor("username")?>
                            <small>Vui lòng nhập tên tài khoản</small>
                        </label>
                        <div>
                            <?php $this->form->textboxFor("username", array('class' => 'validate[required] large'))?>
                            <?php $this->form->validationMessage("username")?>
                        </div>
                        <label>
                            <?php $this->form->labelFor("password")?>
                            <small>Vui lòng nhập mật khẩu nếu bạn muốn thay đổi mật khẩu</small>
                        </label>
                        <div>
                            <?php $this->form->passwordFor("password", array('class' => 'large'))?>
                        </div>
                    </div>                    
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("email")?>
                            <small>Vui lòng nhập email</small>
                        </label>
                        <div> 
                            <?php $this->form->textboxFor("email", array('class' => 'validate[required,custom[email]] large'))?>
                            <?php $this->form->validationMessage("email")?>
                        </div>
                    </div>
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("status")?>
                            <small>Vui lòng chọn</small>
                        </label>
                        <div>
                            <?php $this->form->checkboxFor("status", array("class" => "on_off_checkbox"))?>
				            <?php $this->form->validationMessage("status")?>
                        </div>
                    </div>
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("birthdate")?>
                            <small>Ngày sinh(yyyy-mm-dd)</small>
                        </label>
                        <div> 
                            <?php $this->form->textboxFor("birthdate", array('class' => 'validate[required] large datepicker'))?>
			                <?php $this->form->validationMessage("birthdate")?>
                        </div>
                    </div>
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("gender")?>
                            <small>Vui lòng chọn</small>
                        </label>
                        <div>
                            <?php $this->form->checkboxFor("gender", array("class" => "on_off_checkbox"))?>
				            <?php $this->form->validationMessage("gender")?>
                        </div>
                    </div>
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("phone")?>
                            <small>Vui lòng nhập email</small>
                        </label>
                        <div> 
                            <?php $this->form->textboxFor("phone", array('class' => 'large'))?>
                            <?php $this->form->validationMessage("phone")?>
                        </div>
                    </div>
                    
                    <div class="section ">
                        <label>
                            <?php $this->form->labelFor("yahoo")?>
                            <small>Vui lòng nhập email</small>
                        </label>
                        <div> 
                            <?php $this->form->textboxFor("yahoo", array('class' => 'large'))?>
                            <?php $this->form->validationMessage("yahoo")?>
                        </div>
                    </div>
                    <div class="section">
                        <?php $this->form->labelFor("content")?>
                        <div>
                            <?php $this->form->textareaFor("content", array('id' => 'content-editor'))?>
                        </div>
                    </div>
                    <div class="section last">
                        <div>
                            <input type="submit" class="uibutton submit_form" value="Thêm mới">
                        </div>
                    </div>
                </div>
            </div>
        <?php $this->form->end()?>
        <!-- clear fix -->
        <div class="clear"></div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin('stylesheets')?>
<style type="text/css">
    .cleditorMain{
        height: 180px !important;
    }
</style>
<?php $this->section->end()?>
<?php $this->section->begin("scripts")?>
<?php
//Load js
$this->html->loadJs(array('Content/XMin/components/validationEngine/jquery.validationEngine.js',
                          'Content/XMin/components/validationEngine/jquery.validationEngine-en.js',
                          'Content/XMin/components/editor/jquery.cleditor.js',
                          'Content/XMin/components/elfinder/js/elfinder.full.js',
                          'Scripts/jquery.unobtrusive-ajax.min.js',
                          'Assets/tiny_mce/tiny_mce.js',
                          'Assets/tiny_mce/plugins/imagemanager/js/mcimagemanager.js',
                          'Application/Modules/Page/Assets/js/tinymce.js',
                          'Content/XMin/components/filestyle/jquery.filestyle.js',
                          'Application/Modules/ControlPanel/Assets/js/controlpanel.js',));
?>
<script type="text/javascript">
    $(function(){
        // Select boxes
        $("select").not("select.chzn-select").selectBox();
        $(".fileupload").filestyle();
    });
</script>
<script type="text/javascript">
 function openImageManager(element)
 {
	 mcImageManager.open('Create', element);
 }
   $("#birthdate").datepicker({
    dateFormat: 'yy-mm-dd'
 });
</script>
<?php $this->section->end()?>