<table>
    <tr>
        <td>Gender</td><td><?php if($data->gender===1) echo "Nam"; else echo "Nữ"; ?></td>
    </tr>
    <tr>
        <td>Agemin</td><td><?php echo $data->agemin ?></td>
    </tr>
    <tr>
        <td>Agemax</td><td><?php echo $data->agemax ?></td>
    </tr>
    <tr>
        <td>Bodypoint</td><td><?php echo $data->bodypoint ?></td>
    </tr>
    <tr>
        <td>Body</td><td><?php echo $data->body ?></td>
    </tr>
    <tr>
        <td>Drinkpoint</td><td><?php echo $data->drinkpoint ?></td>
    </tr>
    <tr>
        <td>Drink</td><td><?php echo $data->drink ?></td>
    </tr>
    <tr>
        <td>Photo</td><td><?php echo $data->photo ?></td>
    </tr>
    <tr>
        <td>Heightmin</td><td> <?php echo $data->heightmin ?></td>
    </tr>
    <tr>
        <td>Heightmax</td><td><?php echo $data->heightmax ?></td>
    </tr>
    <tr>
        <td>Eyepoint</td><td><?php echo $data->eyepoint ?></td>
    </tr>
    <tr>
        <td>Eye</td><td><?php echo $data->eye ?></td>
    </tr>
    <tr>
        <td>Hairpoint</td><td><?php echo $data->hairpoint ?></td>
    </tr>
    <tr>
        <td>Hair</td><td><?php echo $data->hair ?></td>
    </tr>
    <tr>
        <td>Backgroundpoint</td><td><?php echo $data->backgroundpoint ?></td>
    </tr>
    <tr>
        <td>Background</td><td><?php echo $data->background ?></td>
    </tr>
    <tr>
        <td>Religiouspoint</td><td><?php echo $data->religiouspoint ?></td>
    </tr>
    <tr>
        <td>Religious</td><td><?php echo $data->religious ?></td>
    </tr>
    <tr>
        <td>Edupoint</td><td><?php echo $data->edupoint ?></td>
    </tr>
    <tr>
        <td>Edu</td><td><?php echo $data->edu ?></td>
    </tr>
    <tr>
        <td>Speakpoint</td><td><?php echo $data->speakpoint ?></td>
    </tr>
    <tr>
        <td>Speak</td><td><?php echo $data->speak ?></td>
    </tr>
    <tr>
        <td>Occupationpoint</td><td><?php echo $data->occupationpoint ?></td>
    </tr>
    <tr>
        <td>Occupation</td><td><?php echo $data->occupation ?></td>
    </tr>
    <tr>
        <td>Incomepoint</td><td><?php echo $data->incomepoint ?></td>
    </tr>
    <tr>
        <td>Income</td><td><?php echo $data->income ?></td>
    </tr>
    <tr>
        <td>Smokepoint</td><td><?php echo $data->smokepoint ?></td>
    </tr>
    <tr>
        <td>Smoke</td><td><?php echo $data->smoke ?></td>
    </tr>
    <tr>
        <td>Relationshippoint</td><td><?php echo $data->relationshippoint ?></td>
    </tr>
    <tr>
        <td>Relationship</td><td><?php echo $data->relationship ?></td>
    </tr>
    <tr>
        <td>Childrenpoint</td><td><?php echo $data->childrenpoint ?></td>
    </tr>
    <tr>
        <td>Children</td><td><?php echo $data->children ?></td>
    </tr>
    <tr>
        <td>Wantchildrenpoint</td><td><?php echo $data->wantchildrenpoint ?></td>
    </tr>
    <tr>
        <td>Wantchildren</td><td><?php echo $data->wantchildren ?></td>
    </tr>
    <tr>
        <td>Piercings</td><td><?php if($data->wantchildren===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Boldness</td><td><?php if($data->boldness===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Brainiacs</td><td><?php if($data->brainiacs===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Rules</td><td><?php if($data->rules===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Dancing</td><td><?php if($data->dancing===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Flirting</td><td><?php if($data->flirting===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Longhair</td><td><?php if($data->longhair===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Money</td><td><?php if($data->money===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Affection</td><td><?php if($data->affection===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Power</td><td><?php if($data->power===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Sarcasm</td><td><?php if($data->sarcasm===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Skinny</td><td><?php if($data->skinny===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Tattoo</td><td><?php if($data->tattoo===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
    <tr>
        <td>Seeker</td><td><?php if($data->seeker===1) echo "Có"; else echo "Không"; ?></td>
    </tr>
</table>