<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico  gray document"></span>Học viên</span> </div>
    <div class="content">
        <div class="load_page tableToolbar">
            <ul class="uibutton-group">
                
            </ul>
            <div class="tableName toolbar">
                <form id="tblForm" method="post" data-delete-url="<?php echo $this->url->action('delete')?>"
                                                 data-edit-url="<?php echo $this->url->action('edit')?>"
                                                 data-hidden-url="<?php echo $this->url->action('hidden')?>">
                    <table class="display" id="data_table" data-ajax-url="<?php echo $this->url->action('index')?>">
                        <thead>
                        <tr>
                            <th width="35">
                                <div class="checksquared"><input type="checkbox" id="checkAll1" class="checkAll" /><label for="checkAll1"></label></div>
                            </th>
                            <th width="150">Avatar</th>
                            <th width="150">Trạng thái</th>
                            <th width="300" align="left">Tài khoản</th>
                            <th width="300" align="left">Chức vụ</th>
                            <th width="100">Ngày đăng ký</th>
                            <th width="100">Quản lý</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>

<?php $this->html->loadJs(array('Scripts/functions.js',
                                'Content/XMin/components/datatables/dataTables.min.js',
                                'Content/XMin/components/datatables/ColVis.js',
                                'Content/XMin/components/datatables/jquery.dataTables.columnFilter.js',
                                'Content/XMin/components/confirm/jquery.confirm.js',
                                'Application/Modules/User/Assets/js/index_controlpanel.js'))?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
    <style type="text/css">
        .aleft{
            text-align: left;
        }
    </style>
<?php $this->section->end()?>