<table>
    <tr>
        <td>Fun</td><td><?php echo $data->fun ?></td>
    </tr>
    <tr>
        <td>Local</td><td><?php echo $data->local ?></td>
    </tr>
    <tr>
        <td>Things</td><td><?php echo $data->things ?></td>
    </tr>
    <tr>
        <td>Đọc sách</td><td><?php echo $data->read ?></td>
    </tr>
    <tr>
        <td>Thể thao</td><td><?php echo $data->sports ?></td>
    </tr>
    <tr>
        <td>Hoạt động</td><td><?php echo $data->activities ?></td>
    </tr>
</table>