<table>
    <tr>
        <td>Relationship</td><td><?php if(isset($data->relationship)&&$data->relationship!=0) echo $relationship[$data->relationship] ?></td>
    </tr>
    <tr>
        <td>Body</td><td><?php if(isset($data->body)&&$data->body!=0) echo $body[$data->body] ?></td>
    </tr>
    <tr>
        <td>Hair</td><td><?php if(isset($data->hair)&&$data->hair!=0) echo $hair[$data->hair] ?></td>
    </tr>
    <tr>
        <td>Chiều cao</td><td><?php if(isset($data->tall)&&$data->tall!=0) echo $tall[$data->tall] ?></td>
    </tr>
    <tr>
        <td>Eyes</td><td><?php if(isset($data->eyes)&&$data->eyes!=0) echo $eyes[$data->eyes] ?></td>
    </tr>
    <tr>
        <td>Headline</td><td><?php echo $data->headline ?></td>
    </tr>
    <tr>
        <td>Description</td><td><?php echo $data->description ?></td>
    </tr>
    <tr>
        <td>Spotlight</td><td><?php if($data->spotlight===1) echo  "Có"; else echo "không"; ?></td>
    </tr>
    <tr>
        <td>Bodyart</td><td> <?php echo $data->bodyart ?></td>
    </tr>
    <tr>
        <td>Feature</td><td><?php if(isset($data->feature)&&$data->feature!=0) echo $feature[$data->feature] ?></td>
    </tr>
    <tr>
        <td>Sign</td><td><?php if(isset($data->sign)&&$data->sign!=0) echo $sign[$data->sign] ?></td>
    </tr>
</table>