<?php $this->content->begin()?>
<div class="widget">
    <div class="header"><span><span class="ico  gray document"></span>Danh sách nguời dùng trên XenForo</span> </div>
    <div class="content">
        <div class="load_page">
            <div class="tableName">
                <form id="tblForm" method="post" data-edit-url="<?php echo $this->url->action('editTeacher')?>"
                                                 data-setteacher-url="<?php echo $this->url->action('setTeacher')?>">
                    <table class="display" id="data_table" data-ajax-url="<?php echo $this->url->action('xfList')?>">
                        <thead>
                        <tr>
                            <th width="35">
                                <div class="checksquared"><input type="checkbox" id="checkAll1" class="checkAll" /><label for="checkAll1"></label></div>
                            </th>
                            <th width="100">Mã thành viên</th>
                            <th width="200">Tên đăng nhập</th>
                            <th width="200">Email</th>
                            <th width="100">Ngày đăng ký</th>
                            <th>Ngày đăng ẩn</th>
                            <th width="100">Quản lý</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $this->content->end()?>
<?php $this->section->begin("scripts")?>
<script type="text/javascript">
    <?php
        $teacher_id = "";
        foreach($teachers as $t)
            $teacher_id .= "'{$t->xf_user_id}',";
        $teacher_id = trim($teacher_id, ',');
    ?>
    var teachers = [<?php echo $teacher_id?>];
</script>
<?php $this->html->loadJs(array('Scripts/functions.js',
                                'Content/XMin/components/datatables/dataTables.min.js',
                                'Content/XMin/components/datatables/ColVis.js',
                                'Content/XMin/components/datatables/jquery.dataTables.columnFilter.js',
                                'Content/XMin/components/confirm/jquery.confirm.js',
                                'Application/Modules/User/Assets/js/xflist_controlpanel.js'))?>
<?php $this->section->end()?>
<?php $this->section->begin("stylesheets")?>
<style type="text/css">
    .aleft{
        text-align: left;
    }
</style>
<?php $this->section->end()?>